### PR TITLE
📚 Documentation: Add Hindi Readme Version

### PR DESCRIPTION
**Pull request by SiddheshKukade**
Added File for Translation of Markdown

## What does this PR do?
Added README translation for HINDI language

## Test Plan
No need to test

## Related PRs and Issues
#4334 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
Yes

### CODE REVIEW

**Comment by SiddheshKukade** [comment]
Dear Maintainers Code is ready for the review

**Comment by SiddheshKukade** [comment]
@eldadfux Sir you can review the code

**Comment by stnguyen90** [comment]
@SiddheshKukade Thanks for raising this PR! 🙏 Unfortunately, this is not something we want to move forward at the moment as it would be difficult for us to maintain. We'll be sure to revisit this in the future when appropriate. For now, I'm going to close this to avoid attention during Hacktoberfest.

**Comment by SiddheshKukade** [comment]
@stnguyen90 I can Understand.

**Pull request closed without merging**
