### PR TITLE
feat-dart-env-update

### PR DESCRIPTION
**Pull request by lohanidamodar**
## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

### CODE REVIEW

**Comment by lohanidamodar** [comment]
@eldadfux is the failure because the new ENV is not pushed to docker hub?

**Comment by eldadfux** [comment]
> @eldadfux is the failure because the new ENV is not pushed to docker hub?

Yes.

**Review by TorstenDittmann — APPROVED** [review]
👍🏻

**Comment by lohanidamodar** [comment]
@eldadfux can you please restart the test.

**Comment by TorstenDittmann** [comment]
> @eldadfux can you please restart the test.

Restarted 👍🏻

**Pull request merged**
