### PR TITLE
Feat zoom oauth

### PR DESCRIPTION
**Pull request by lohanidamodar**
## What does this PR do?

Adds Zoom OAuth2 Adapter

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

YES

### CODE REVIEW

**Review by christyjacob4 — APPROVED** [review]
Looks good ! Awesome work :)

**Review by Meldiron — APPROVED** [review]
LGTM. Have you done manual QA?
Did you try both login, and get&refresh accessToken?

**Comment by lohanidamodar** [comment]
> Looks good ! Awesome work :)

I was done in like 10 mins + 10 mins testing. Awesome work on the Adapter by the way.

**Comment by lohanidamodar** [comment]
> LGTM. Have you done manual QA? Did you try both login, and get&refresh accessToken?

Probably need to test the refreshing part. Rest I tested.

**Comment by lohanidamodar** [comment]
Merging, manually tested and verified.

**Pull request merged**
