### PR TITLE
Use official Hungarian names of countries; fix email template grammar

### PR DESCRIPTION
**Pull request by balazsbotond**
I don't know if there are any Hungarians on this project but in the very probable case that there aren't any, I'll try to describe why I made each change so you can see that these aren't just random changes :)

### "hu" locale

I used the [official rules](https://helyesiras.mta.hu/helyesiras/default/akh12) for writing compound words longer than 6 syllables with a hyphen. The other two changes are fixing a grammatic error and applying common capitalization conventions.

### Email templates

- I used the formal voice because appwrite is a general tool; we shouldn't assume that users can be addressed informally
- I replaced the word "ignorál" which sounds very unnatural in Hungarian, with the expression "tekintse tárgytalannak"
- I rewrote the text to flow more naturally and placed the variables in grammatically correct positions

### Country names

I noticed that a lot of countries had incorrect names. I changed them to use the official spelling:

| Before         | After          | Reference                                            |
|----------------|----------------|------------------------------------------------------|
| Bulgaria       | Bulgária       | https://hu.wikipedia.org/wiki/Bulg%C3%A1ria        |
| Algíria        | Algéria        | https://hu.wikipedia.org/wiki/Alg%C3%A9ria         |
| Guinea\-Bissau | Bissau\-Guinea | https://hu.wikipedia.org/wiki/Bissau\-Guinea       |
| Kazakhsztán    | Kazahsztán     | https://hu.wikipedia.org/wiki/Kazahszt%C3%A1n      |
| Dél Korea      | Dél\-Korea     | https://hu.wikipedia.org/wiki/D%C3%A9l\-Korea      |
| Kuwait         | Kuvait         | https://hu.wikipedia.org/wiki/Kuvait               |
| Sri Lanka      | Srí Lanka      | https://hu.wikipedia.org/wiki/Sr%C3%AD\_Lanka      |
| Luxembourg     | Luxemburg      | https://hu.wikipedia.org/wiki/Luxemburg            |
| Nigeria        | Nigéria        | https://hu.wikipedia.org/wiki/Nig%C3%A9ria         |
| Nikaragua      | Nicaragua      | https://hu.wikipedia.org/wiki/Nicaragua            |
| Qatar          | Katar          | https://hu.wikipedia.org/wiki/Katar                |
| Rwanda         | Ruanda         | https://hu.wikipedia.org/wiki/Ruanda               |
| Szurinám       | Suriname       | https://hu.wikipedia.org/wiki/Suriname             |
| Swaziland      | Szváziföld     | https://hu.wikipedia.org/wiki/Szv%C3%A1zif%C3%B6ld |
| Tájföld        | Thaiföld       | https://hu.wikipedia.org/wiki/Thaif%C3%B6ld        |
| Tanzania       | Tanzánia       | https://hu.wikipedia.org/wiki/Tanz%C3%A1nia        |
| Ukraina        | Ukrajna        | https://hu.wikipedia.org/wiki/Ukrajna              |
| Yemen          | Jemen          | https://hu.wikipedia.org/wiki/Jemen                |

### CODE REVIEW

**Comment by eldadfux** [comment]
Hey @balazsbotond this PR looks awesome, but please submit it to branch `0.7.x` where we have changed the translations file structure a little bit. You can find more info here #25

**Comment by balazsbotond** [comment]
@eldadfux Thank you, looks like I haven't read that thread carefully enough 😅

I'll update it later today.

**Comment by balazsbotond** [comment]
I think it's easier to close this PR and create a new one from a branch based on `0.7.x`.

**Comment by balazsbotond** [comment]
I've put up a new PR based on `0.7.x`: #642 

Sorry about the noise on this one.

**Pull request closed without merging**
