### PR TITLE
chore: enhance gitpod Dockerfile steps for prebuilds

### PR DESCRIPTION
**Pull request by emattiza**
## What does this PR do?

Support quicker gitpod workspace prebuild and load for users

## Test Plan

Largely iterative building and executing within the workspace to get an idea of average performance and if improvement in time to coding can be lowered

## Related PRs and Issues

Slow workspace prebuilds reported in Gitpod discord.

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes!

### CODE REVIEW

**Review by brandonroberts — APPROVED** [review]
LGTM

**Comment by brandonroberts** [comment]
Thanks @emattiza!

**Comment by emattiza** [comment]
> Thanks @emattiza!

Thanks @brandonroberts! This was in working with @Meldiron over in the gitpod discord, but we may have solutions to help load prebuilds faster that we talked about in Discord. I don't believe the prebuild slowness was an issue (20m to construct a prebuild, largely happens out of the user's eye) so much as loading of the prebuild itself into a fresh workspace (was taking 2-3mins for Meld, basically a long hang in a loading screen on start from clicking gitpod button). We talked about adding the incremental prebuilds feature to the gitpod project itself to support some enhancement of background prebuilds, but ultimately this was a larger gitpod issue that was occuring with the platform for other users, and is needed to be addressed by Gitpod staff directly.

All that to say, i mostly made this pr to iterate the existing prebuild config and see what improvements could be made. But i did so under the wrong pretext, and have now found a different platform issue that this PR will not address. I don't feel these changes need to be in the repo, and the issue will likely be resolved via Gitpod support in their public platform. 

I'm happy to gift some of the work here if it seems ok to your team, but this doesn't address the problem exactly, and I don't want to insert change unnecessarily.

**Comment by brandonroberts** [comment]
> > Thanks @emattiza!
> 
> Thanks @brandonroberts! This was in working with @Meldiron over in the gitpod discord, but we may have solutions to help load prebuilds faster that we talked about in Discord. I don't believe the prebuild slowness was an issue (20m to construct a prebuild, largely happens out of the user's eye) so much as loading of the prebuild itself into a fresh workspace (was taking 2-3mins for Meld, basically a long hang in a loading screen on start from clicking gitpod button). We talked about adding the incremental prebuilds feature to the gitpod project itself to support some enhancement of background prebuilds, but ultimately this was a larger gitpod issue that was occuring with the platform for other users, and is needed to be addressed by Gitpod staff directly.
> 
> All that to say, i mostly made this pr to iterate the existing prebuild config and see what improvements could be made. But i did so under the wrong pretext, and have now found a different platform issue that this PR will not address. I don't feel these changes need to be in the repo, and the issue will likely be resolved via Gitpod support in their public platform.
> 
> I'm happy to gift some of the work here if it seems ok to your team, but this doesn't address the problem exactly, and I don't want to insert change unnecessarily.

Thanks for the further background on the changes. I still think the PR adds some value in slimming down the steps for building the underlying image, so I'm good with continuing with getting it merged if you are. If anything, this getting fixed upstream in Gitpod as a seamless upgrade for us is even better.

**Review by eldadfux — APPROVED** [review]

**Review by Meldiron — APPROVED** [review]

**Comment by eldadfux** [comment]
Thanks for the contribution @emattiza!

**Pull request merged**
