### PR TITLE
doc(tutorials/add-storage-adapter) -------> fixed typo

### PR DESCRIPTION
**Pull request by Biki-das**
envorinment -------> environment

### CODE REVIEW

**Comment by Biki-das** [comment]
@TorstenDittmann  please review!

**Comment by Biki-das** [comment]
> envorinment -------> environment

@eldadfux could you review please?

**Review by PineappleIOnic — APPROVED** [review]

**Comment by Biki-das** [comment]
> > envorinment -------> environment
> 
> @eldadfux could you review please? 

@PineappleIOnic  can it be merge or it needs more changes?

**Comment by Biki-das** [comment]
> > > envorinment -------> environment
> > 
> > @eldadfux could you review please? 
> 
> @PineappleIOnic  can it be merge or it needs more changes? 

@christyjacob4  please review

**Comment by christyjacob4** [comment]
THANK YOU so much! All changes merged 🥳

**Pull request merged**
