### PR TITLE
Delete user endpoint

### PR DESCRIPTION
**Pull request by TorstenDittmann**
First draft of the feature #378.

Following things will be added after first review:

- take advantage of the delete worker
- write tests
- write documentation

### CODE REVIEW

**Comment by TorstenDittmann** [comment]
Gonna start writing the tests today 👍 So there will be progress again 😉

**Comment by eldadfux** [comment]
Hey @TorstenDittmann, do you think you could give this another push? if not in the next few days you can push what you've done so far and I can complete and adjust it for 0.7

**Comment by TorstenDittmann** [comment]
Will do! I had too much distraction the past few weeks. Tests should be done, just needs some revise in general :+1:

**Comment by eldadfux** [comment]
Sure, let me know if I can help when your'r on it

**Pull request merged**
