### PR TITLE
Update doc folder database to databases 

### PR DESCRIPTION
**Pull request by gewenyu99**
## What does this PR do?

After the Database service is renamed to Databases, we missed a folder's rename, breaking the API docs.

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

### CODE REVIEW

**Comment by gewenyu99** [comment]
> Did the specs generate with the descriptions after making this change?

Testing the homepage rn ;)

**Comment by gewenyu99** [comment]
@TorstenDittmann I doesn't look like folder name alone is the issue. Where do we render these .md files in homepage?

**Comment by stnguyen90** [comment]
@gewenyu99, did you get a chance to check if the generated specs has the descriptions?

**Comment by gewenyu99** [comment]
Screen Shot 2022-07-14 at 4 18 50 PM
Annnnnd it works!

**Comment by gewenyu99** [comment]
@stnguyen90 Resolved the merge conflict.

**Comment by eldadfux** [comment]
We need to push a new 0.15.x release. ASAP.

**Pull request merged**
