### PR TITLE
Update environment-variables.md

### PR DESCRIPTION
**Pull request by sakshamtaneja21**

### CODE REVIEW

**Comment by sakshamtaneja21** [comment]
hey 
please review it

**Comment by eldadfux** [comment]
Merged! Thank you!

**Comment by sakshamtaneja21** [comment]
how can I get an invite of your GitHub organization as a member

**Comment by sakshamtaneja21** [comment]
medium.com/appwrite-io/hacktoberfest-2019-is-almost-here-lets-celebrate-it-together-24b311236dd
may i know about it when will receive swags

**Comment by sakshamtaneja21** [comment]
how can I get an invite of your GitHub organization as a member

**Comment by eldadfux** [comment]
@sakshamtaneja21 iI sent you an invite, check your email or accept at here: https://github.com/orgs/appwrite/invitation

The swags should arrive in a few weeks. We have just finalized our list and about to send them all.

**Pull request merged**
