### PR TITLE
feat: add notion oauth provider

### PR DESCRIPTION
**Pull request by christyjacob4**
## What does this PR do?

Adds Notion as a new OAuth provider

Screenshot 2022-01-16 at 2 49 09 AM

## Test Plan

Use Existing tests

## Related PRs and Issues
NA

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

YES

### CODE REVIEW

**Comment by eldadfux** [comment]
For consistency, it would be great to use a logo with a grey or a dark background and white logo.

**Comment by christyjacob4** [comment]
@eldadfux  let me check if they have something relevant in their media kit

**Comment by christyjacob4** [comment]
Screenshot 2022-01-16 at 2 55 05 PM



What do you think @eldadfux

**Comment by eldadfux** [comment]
👌

**Review by eldadfux — APPROVED** [review]

**Pull request merged**
