### PR TITLE
Fix issue #30 and #5

### PR DESCRIPTION
**Pull request by christyjacob4**
1) Added support for Google OAuth
2) Refactored code using php-cs-fixer
3) Added Content Length in the header for all requests made by the OAuth Class.
change1
4) Corrected the spelling Mistake in "Adding OAuth Providers" Docs.
change2

### CODE REVIEW

**Comment by eldadfux** [comment]
Amazing job @christyjacob4, Thank you! 🥳

**Comment by christyjacob4** [comment]
Thanks a lot!! @eldadfux

**Comment by christyjacob4** [comment]
closes #30

**Comment by christyjacob4** [comment]
Nostalgia :smiley:

**Pull request merged**
