### PR TITLE
Add IT Locale

### PR DESCRIPTION
**Pull request by tacoelho**

### CODE REVIEW

**Comment by tacoelho** [comment]
Could you please merge it on Oct 1st for Hacktoberfest? :D

**Comment by eldadfux** [comment]
Hey @tacoelho please send one pull request for all the IT locale

**Comment by tacoelho** [comment]
#

> Hey @tacoelho please send one pull request for all the IT locale

Just did it!

**Comment by tacoelho** [comment]
I´m closing this one, thanks!

**Pull request closed without merging**
