### PR TITLE
Changes for Urdu Language

### PR DESCRIPTION
**Pull request by navneetsn18**
Related to #25 

@eldadfux I have translated **appwrite** locale and email templates in Urdu.

Please review the changes and let me know if any fixes required.

### CODE REVIEW

**Comment by spielers** [comment]
@navneetsn18 I suggest make translation PR to 0.7.x branch rather than the master branch ask @eldadfux  before making PR.

**Comment by navneetsn18** [comment]
@spielers okk i'll do that

**Comment by spielers** [comment]
You can look at the description of the issue.

**Comment by spielers** [comment]
@navneetsn18  I request You to delete this PR Because you already created a new one for The  0.7.x branch!

**Comment by spielers** [comment]
@navneetsn18 Now you can delete this PR, you have already created a new one to the 0.7.x branch 
Best,
spielers

**Comment by navneetsn18** [comment]
@spielers I just need to close this PR. Right..

**Pull request closed without merging**
