### PR TITLE
Change Appwrite Cookie Name

### PR DESCRIPTION
**Pull request by eldadfux**
## What does this PR do?

Had some unexplained issues with Safari blocking the Appwrite console cookie on non-https connections. Not sure why, but the only thing fixing it was to change our cookie name. Safari cookie blocking console cookie had been reported by another user on Discord, not sure its related

## Test Plan

Manual tested

## Related PRs and Issues

None

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Review by christyjacob4 — APPROVED** [review]
LGTM 👍

**Comment by eldadfux** [comment]
@TorstenDittmann can you check if you have any cookie related issues when trying to login to the Appwrite console from Safari on http or https?

**Comment by TorstenDittmann** [comment]
> @TorstenDittmann can you check if you have any cookie related issues when trying to login to the Appwrite console from Safari on http or https?

No problem at all for me 🤔

**Comment by eldadfux** [comment]
I guess we can still think of merging this change - shorter cookie name is not a bad feature. Will require users to re-login, but that should be a legit request from time to time

**Comment by TorstenDittmann** [comment]
> I guess we can still think of merging this change - shorter cookie name is not a bad feature. Will require users to re-login, but that should be a legit request from time to time

If we want to merge it, then 0.8 is the way to go since due to the the session collection we invalidate all logins anyway.

**Review by TorstenDittmann — APPROVED** [review]

**Comment by eldadfux** [comment]
Closing for now.

**Pull request closed without merging**
