### PR TITLE
Update add-oauth2-provider.md

### PR DESCRIPTION
**Pull request by tusharxoxoxo**
## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

### CODE REVIEW

**Comment by tessamero** [comment]
these changes are good on my end

**Review by gewenyu99 — APPROVED** [review]

**Comment by gewenyu99** [comment]
@tusharxoxoxo Hi there.

Thank you for contributing to Appwrite ❤️ !

We appreciate your contributions, but I wanted to let you know we only count one grammar-related PRs from a user as `hacktoberfest-accepted`. If you see some of your PRs marked `invalid`, it just means we're accepting these changes, but they don't count toward Hacktoberfest.

Happy hacking!

**Comment by tusharxoxoxo** [comment]
Ok, thanks

**Comment by PineappleIOnic** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Comment by stnguyen90** [comment]
@tusharxoxoxo would you please sync with master to ensure the CI job passes?

**Comment by tusharxoxoxo** [comment]
sure

**Review by christyjacob4 — APPROVED** [review]

**Pull request merged**
