### PR TITLE
Adding Darija (Moroccan Arabic) translation file

### PR DESCRIPTION
**Pull request by Achraf112Ben**
## What does this PR do?

This PR provides the ar-ma.json translation file for Moroccan Arabic local.

## Test Plan

N/A

## Related PRs and Issues

- (Related PR or issue)

## Checklist

- [x] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [ ] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

### CODE REVIEW

**Comment by Achraf112Ben** [comment]
@eldadfux @gewenyu99 @stnguyen90 
Hello guys, 

This pull request containing the translation file for Moroccan Darija (Moroccan Arabic) has waiting since January without approval.
What would it take to be approved? 
I'm really in a dire need for the Darija translation for my future projects.

Regards.

**Comment by stnguyen90** [comment]
@Achraf112Ben, thanks for submitting this PR! 🙏🏼 It would help if there was someone else who was a native speaker who could validate the translation.

**Comment by maurusian** [comment]
I'm a native speaker of Darija and I can validate the translation by @Achraf112Ben. Just give me some time, and I will do it within the next few days.

**Comment by Achraf112Ben** [comment]
Hi @maurusian how is the review going on?

**Comment by AbdelNAsr** [comment]
Hi, I'm actually a Darija native speak, and I approve this translation @stnguyen90

**Review by stnguyen90 — APPROVED** [review]

**Comment by Achraf112Ben** [comment]
Hi @stnguyen90, thank you for the merge, which release can I expect it to?

**Pull request merged**
