### PR TITLE
Add Mastodon as an oauth2 provider

### LINKED ISSUE #3878: 🚀 Feature: Add Mastodon as an authentication method
### 🔖 Feature description

Add authentication via Mastodon using their [OAuth2 API](https://docs.joinmastodon.org/spec/oauth/)

Mastodon is a federated service, so it would require the Mastodon instance you want to allow people to login under

### 🎤 Pitch

Allowing people to use Mastodon as an authentication method would allow for communities to have one account to login under everything

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by grahhnt**
## What does this PR do?
This PR adds [Mastodon](https://joinmastodon.org) oAuth2 support

## Test Plan

I've created a test app that will attempt to login with the oAuth2 provider.

## Related PRs and Issues

Closes #3878 

### Have you added your change to the [Changelog](https://github.com/appwrite/appwrite/blob/master/CHANGES.md)?

I didn't make changes to the master branch, I don't think I need to modify that.

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by PineappleIOnic** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Comment by christyjacob4** [comment]
@grahhnt thanks a lot for your contributions during Hacktoberfest 2022! 

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord. 

This PR needs some more work ever since we moved the appwrite console to https://github.com/appwrite/console

You can take a look at this PR for reference https://github.com/appwrite/console/pull/213

**Comment by h0lybyte** [comment]
Epic! I can not wait for this to be added!

**Comment by grahhnt** [comment]
I apologize but I don't have time to update this to the newer appwrite console. If someone else is able to take it, that would be great!

**Comment by christyjacob4** [comment]
Closing this PR for now. Feel free to reopen the PR if you find time to work on it.

**Pull request closed without merging**
