### PR TITLE
Fixing PSR in Docker Library 

### PR DESCRIPTION
**Pull request by mendoza**
## What does this PR do?
Just made sure the code is following the PSR issues

## Test Plan
Ran the tests
`docker-compose exec appwrite test`

## Related PRs and Issues

Issue #1942 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
Yes

### CODE REVIEW

**Comment by christyjacob4** [comment]
@mendoza  Please create your PR after you've been assigned to an issue.

**Comment by mendoza** [comment]
sorry will do it again

**Comment by mendoza** [comment]
sorry you are right

**Comment by papuruth** [comment]
Hey, can I take this too? If it's okay?

**Pull request closed without merging**
