### PR TITLE
Add tutorial for how to add SMS provider

### PR DESCRIPTION
**Pull request by stnguyen90**
## What does this PR do?

Add tutorial for how to add SMS provider based off the oauth tutorial

## Test Plan

Manual

## Related PRs and Issues

None

### Have you added your change to the [Changelog](https://github.com/appwrite/appwrite/blob/master/CHANGES.md)?

Not needed

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Review by maharshi-sinha — APPROVED** [review]
Looks good to me!

**Comment by stnguyen90** [comment]
Closing as the SMS code is being migrated to the [Utopia Messaging](https://github.com/utopia-php/messaging) library and there is already a [tutorial](https://github.com/utopia-php/messaging/blob/main/docs/add-new-adapter.md) in that repo for adding a provider.

**Comment by stnguyen90** [comment]
Actually, we might still want some documentation for updates in Appwrite when a new provider is added.

**Comment by stnguyen90** [comment]
Things are changing quite a big for messaging. We'll revisit this later.

**Pull request closed without merging**
