### PR TITLE
[API] Locale - List languages - ISO 639-1

### PR DESCRIPTION
**Pull request by TorstenDittmann**
- list all languages classified by ISO 639-1

- possible features
   - add a "common" property to sort out mostly unknown languages and display only the most common ones

#351

### CODE REVIEW

**Comment by eldadfux** [comment]
Wow this was fast. Any chance you could also add the e2e test?

This is where the locale test are located: https://github.com/appwrite/appwrite/blob/7532a96bb3fb9a9eb77273998f6a4b987e2c1e5a/tests/e2e/Services/Locale/LocaleBase.php#L9

We can run the tests with `docker exec [appwrite-dev-container-id] test`

**Comment by TorstenDittmann** [comment]
Sure!

**Comment by TorstenDittmann** [comment]
@eldadfux Alright, after some back and forth the test is integrated 👍

**Comment by eldadfux** [comment]
Amazing work! You are now certified for PHP 😉

Waiting with the merge, I'm not sure if we want this in 0.6.2 or 0.7 yet.

**Comment by eldadfux** [comment]
Figured out that this feature requires a new release for all the SDKs, so it will make more sense to release it with 0.7

**Comment by eldadfux** [comment]
Merged 🥳

**Pull request merged**
