### PR TITLE
Fix platforms zone not aligning with statistics

### PR DESCRIPTION
**Pull request by didair**
## What does this PR do?
Adjusts the zone for platform to align with the zone above it.

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
Yes

### CODE REVIEW

**Comment by TorstenDittmann** [comment]
Hey @didair 👋🏻 

Thanks for the contribution!

Can you provide a _before_ and _after_ screenshot? 🙂

**Comment by didair** [comment]
Sure!

Before:
bild

After:
bild


... and on narrow screens:
bild

**Comment by eldadfux** [comment]
Well... actually this was an intended design feature 😅  if it so bad, we can reconsider hehe

**Comment by didair** [comment]
I understand 👍🏼 Its your decision - Im just happy to contribute whatever I can

**Pull request closed without merging**
