### PR TITLE
docs: update windows powershell commands

### PR DESCRIPTION
**Pull request by vimode**
## What does this PR do?

Updated the windows powershell commands, in powershell a new line is done via backticks(`). The current guide uses commas(,) for new line instead. 
The README.md has the correct commands but the README-CN.md has the incorrect command.

Current 
```bash
docker run -it --rm ,
    --volume /var/run/docker.sock:/var/run/docker.sock ,
    --volume ${pwd}/appwrite:/usr/src/code/appwrite:rw ,
    --entrypoint="install" ,
    appwrite/appwrite:1.0.3
```
Updated with backticks. 
```bash
docker run -it --rm `
    --volume /var/run/docker.sock:/var/run/docker.sock `
    --volume ${pwd}/appwrite:/usr/src/code/appwrite:rw `
    --entrypoint="install" `
    appwrite/appwrite:1.0.3
```

This aligns with the current proper installation instructions given in the [README.md.](https://github.com/appwrite/appwrite#windows)

## Related PRs and Issues

This has been discussed in #315 
The same issue in the official docs which is updated in a PR at [appwrite/docs/#291.](https://github.com/appwrite/docs/pull/291)

### Have you added your change to the [Changelog](https://github.com/appwrite/appwrite/blob/master/CHANGES.md)?

This doesn't change the codebase, so I don't think its needed to be added to changelog. 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by gewenyu99** [comment]
I think this exists in README.md, too, right? 

Can we have this change in both places?

**Comment by vimode** [comment]
The code in the [README.md](https://github.com/appwrite/appwrite#windows) uses the correct convention (uses backticks) for new line.

**Review by stnguyen90 — APPROVED** [review]
Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

**Comment by christyjacob4** [comment]
@vimode can you please resolve the conflicts?

**Comment by vimode** [comment]
@christyjacob4 I have resolved the merge conflicts.

**Review by christyjacob4 — APPROVED** [review]

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

**Pull request merged**
