### PR TITLE
chore: remove compose version

### PR DESCRIPTION
**Pull request by loks0n**
Clears warning warning about using version key in docker-compose.yaml

Using docker compose `version` key is obsolete:
https://github.com/compose-spec/compose-spec/blob/master/spec.md#version-and-name-top-level-elements

### CODE REVIEW

**Review by stnguyen90 — COMMENTED** [review]
How about here too:

https://github.com/appwrite/appwrite/blob/33587a2a37f4671d6c008d0f5719e3c7bfb4f471/app/views/install/compose.phtml#L14

**Comment by stnguyen90** [comment]
Looks like a test needs to be updated.

**Comment by stnguyen90** [comment]
@loks0n please remember to re-request a review when your PR is ready to be reviewed again.

**Review by stnguyen90 — APPROVED** [review]

**Comment by stnguyen90** [comment]
I can confirm the compose file generated fine and the containers can start successfully: 

image

**Review by abnegate — APPROVED** [review]

**Pull request merged**
