### PR TITLE
Fixes: #30

### PR DESCRIPTION
**Pull request by christyjacob4**
The mistake in the path has been fixed.

### CODE REVIEW

**Comment by eldadfux** [comment]
@christyjacob4 this pull request also includes the Gitlab and Google OAuth adapters, are their ready? Do you want to move them to a separate pull request?

**Comment by christyjacob4** [comment]
No they aren't ready yet. I just started my work on it.. what do you suggest?

**Comment by eldadfux** [comment]
@christyjacob4 Whatever works for you, just let me know when ready and I can start review and merge the changes.

**Comment by christyjacob4** [comment]
Is it okay to leave this pull request like this? Or do you want me to remove the oAuth stuff and then raise one more pull request? @eldafux

**Comment by eldadfux** [comment]
You can leave it like this. Just notice, I will only be able to merge this PR once you finish implementing the new OAuth providers because right now they will be shown in the console while they aren't working.

**Comment by christyjacob4** [comment]
Okay @eldadfux noted :)

**Comment by christyjacob4** [comment]
The spelling correction along with the Addition of Google OAuth will be pushed in  a new PR. Hence I'm closing this issue.

**Pull request closed without merging**
