### PR TITLE
Fix user empty name

### PR DESCRIPTION
**Pull request by eldadfux**
## What does this PR do?

Added a placeholder when user name is empty to allow navigation.

## Test Plan

N/A

## Related PRs and Issues

#1204 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes.

### CODE REVIEW

**Comment by eldadfux** [comment]
image

**Comment by eldadfux** [comment]
Changed `-----` to `Unknown` for consistency

**Comment by TorstenDittmann** [comment]
Can we do _Anonymous User_  and _Unknown_ italic?

Since they are supposed to be placeholders 🤔

**Comment by eldadfux** [comment]
> Can we do _Anonymous User_ and _Unknown_ italic?
> 
> Since they are supposed to be placeholders 🤔

Italic looks kind of bad with the dashboard style, what about adding square brackets like `[ Unknown ]`?

image

**Comment by TorstenDittmann** [comment]
> > Can we do _Anonymous User_ and _Unknown_ italic?
> > Since they are supposed to be placeholders 🤔
> 
> Italic looks kind of bad with the dashboard style, what about adding square brackets like `[ Unknown ]`?
> 
> image

 Not a 100% sure about the [] or italic. In the end we should just make sure they are different from someone with the name `Unknown` or `Anonymous User` 🤔

**Pull request merged**
