### PR TITLE
Added description and removed blank lines.

### PR DESCRIPTION
**Pull request by MdHanif01**
Added description of some words to help users understand better and also removed some blank spaces.

### CODE REVIEW

**Comment by eldadfux** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on Gitter if you would like me to send you some cool Appwrite stickers and magnets!

**Comment by eldadfux** [comment]
Hey @MdHanif01 , we really appreciate your time and willingness to contribute to open-source, but this is not the kind of PR's that we need at the moment.

If you still wish to help us by creating meaningful pull requests, go over our open issues and see if there is any topic that you might be interested in helping.

**Comment by MdHanif01** [comment]
Hey Eldad A FUX,

Thanks for merging the pull request.

I'll try ti contribute as much as I can.

Can you please share the link of your gitter account so that I can
communicate easily for awesome stickers and magnets.

Thank you.
Hanif.

**Comment by eldadfux** [comment]
You can just search my username on gitter: eldadfux

**Pull request closed without merging**
