### PR TITLE
Update Unique ID references in docs from magic string to ID.unique()

### PR DESCRIPTION
**Pull request by gewenyu99**
## What does this PR do?

This PR updates the docs to use new helper functions. This change will not reflect on the existing 1.0.x docs, but will reflect when we update the specs in the future.

Before Change:
Screen Shot 2022-10-03 at 5 30 18 PM

After Change
Screen Shot 2022-10-03 at 5 33 44 PM

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

### CODE REVIEW

**Review by stnguyen90 — APPROVED** [review]

**Comment by Meldiron** [comment]
Test

**Review by eldadfux — APPROVED** [review]

**Comment by stnguyen90** [comment]
womp. merge conflicts.

**Comment by gewenyu99** [comment]
> womp. merge conflicts.

Took changes in master. These changes won't be reflected until 1.1 since we're not touching 1.0 specs :)

**Comment by eldadfux** [comment]
Re-run tests

**Pull request merged**
