### PR TITLE
doc-1409-teams-membership-parameter-order

### PR DESCRIPTION
**Pull request by deshankoswatte**
## What does this PR do?

Fixes parameter order at create-team-membership method.

## Related PRs and Issues

- Fixes: https://github.com/appwrite/appwrite/issues/1409
- Fixes: https://github.com/appwrite/appwrite/issues/1505
- Fixes: https://github.com/appwrite/appwrite/issues/1669

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
Yes

### CODE REVIEW

**Review by TorstenDittmann — CHANGES_REQUESTED** [review]
Thank you for your contribution!

There is one thing that needs to be adapted as well, the order of this like => https://github.com/appwrite/appwrite/blob/e1235299f52123a01cb50f3d185836c6fcec4bf4/app/controllers/api/teams.php#L275

With this change `$name` will now be after `$url` 👍🏻

**Comment by deshankoswatte** [comment]
> Thank you for your contribution!
> 
> There is one thing that needs to be adapted as well, the order of this like =>
> 
> https://github.com/appwrite/appwrite/blob/e1235299f52123a01cb50f3d185836c6fcec4bf4/app/controllers/api/teams.php#L275
> 
> With this change `$name` will now be after `$url` 👍🏻

Hi @TorstenDittmann,

Will do the changes right away. Thank you for pointing it out.

**Comment by deshankoswatte** [comment]
Hi @TorstenDittmann,

I addressed the mentioned changes through https://github.com/appwrite/appwrite/pull/1818/commits/f31fc0735ed1b0a858eac185e7a3ec19f90c7dac.

**Review by lohanidamodar — APPROVED** [review]

**Review by TorstenDittmann — APPROVED** [review]

**Comment by eldadfux** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me (`eldadfux`) on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! 

As a way of saying thank you, we have just invited you to join the Appwrite organization on GitHub. You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) to help make Appwrite better.

**Comment by eldadfux** [comment]
@lohanidamodar @TorstenDittmann thanks for reviewing!!

**Comment by deshankoswatte** [comment]
> THANK YOU! All changes merged partying_face
> 
> Please reach out to me (`eldadfux`) on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! 
> 
> As a way of saying thank you, we have just invited you to join the Appwrite organization on GitHub. You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.
> 
> You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.
> 
> Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) to help make Appwrite better.

Thank you @eldadfux, @lohanidamodar, and @TorstenDittmann for the appreciation.

**Pull request merged**
