### PR TITLE
Added missing env vars

### PR DESCRIPTION
**Pull request by eldadfux**
## What does this PR do?

Added some missing optional env vars from the setup compose file. This PR adds to make sure devs don't need to update both .env and docker-compose.yml file to get a feature working.

## Test Plan

N/A

## Related PRs and Issues

Issue raised on Discord

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by TorstenDittmann** [comment]
Can we auto generate where the values have to be?

We could add a service property to our variables which would define the to be exposed variables for the services.

```php
[
    'name' => '_APP_DOMAIN_TARGET',
    'description' => 'A DNS A record hostname to serve as a CNAME target for your Appwrite custom domains. You can use the same value as used for the Appwrite \'_APP_DOMAIN\' variable. The default value is \'localhost\'.',
    'introduction' => '',
    'default' => 'localhost',
    'required' => true,
    'question' => 'Enter a DNS A record hostname to serve as a CNAME for your custom domains.\nYou can use the same value as used for the Appwrite hostname.',
    'services' => [
        'appwrite', 'appwrite-certificates-worker',....
    ],
],
```

**Comment by eldadfux** [comment]
> Can we auto generate where the values have to be?
> 
> We could add a service property to our variables which would define the to be exposed variables for the services.
> 
> ```
> [
>     'name' => '_APP_DOMAIN_TARGET',
>     'description' => 'A DNS A record hostname to serve as a CNAME target for your Appwrite custom domains. You can use the same value as used for the Appwrite \'_APP_DOMAIN\' variable. The default value is \'localhost\'.',
>     'introduction' => '',
>     'default' => 'localhost',
>     'required' => true,
>     'question' => 'Enter a DNS A record hostname to serve as a CNAME for your custom domains.\nYou can use the same value as used for the Appwrite hostname.',
>     'services' => [
>         'appwrite', 'appwrite-certificates-worker',....
>     ],
> ],
> ```

The more I think of it lately, it seems like we can't avoid a containers.php config file, no?

**Comment by TorstenDittmann** [comment]
> > Can we auto generate where the values have to be?
> > We could add a service property to our variables which would define the to be exposed variables for the services.
> > ```
> > [
> >     'name' => '_APP_DOMAIN_TARGET',
> >     'description' => 'A DNS A record hostname to serve as a CNAME target for your Appwrite custom domains. You can use the same value as used for the Appwrite \'_APP_DOMAIN\' variable. The default value is \'localhost\'.',
> >     'introduction' => '',
> >     'default' => 'localhost',
> >     'required' => true,
> >     'question' => 'Enter a DNS A record hostname to serve as a CNAME for your custom domains.\nYou can use the same value as used for the Appwrite hostname.',
> >     'services' => [
> >         'appwrite', 'appwrite-certificates-worker',....
> >     ],
> > ],
> > ```
> 
> The more I think of it lately, it seems like we can't avoid a containers.php config file, no?

Sounds reasonable 👍🏻

**Comment by eldadfux** [comment]
OK, I'll merge this PR and open a new issue on Asana.

**Pull request merged**
