### PR TITLE
Twitter Guide added

### PR DESCRIPTION
**Pull request by ShivamRawat0l**
I am new to open source. I have added the api to authenticate using twitter. 
If I could have an guide/mentor I will try to add it myself.

### CODE REVIEW

**Comment by christyjacob4** [comment]
Have you tested the implementation @ShivamRawat0l

**Comment by ShivamRawat0l** [comment]
Sir , I just contains the routes of twitter api currently. I would like to have a mentor to understand it better. 
Currently it does not work just contains the p
routes

**Comment by christyjacob4** [comment]
You can test out your adapter by performing a user registration flow. 
1) Create a sample project
2) Navigate to Users > Providers
3) Create a project on Twitter and get the APP ID and APP secret
4) Enter it in the providers and save it. If you get a green toast message, you're good to go .
5) Navigate to this URL 
http://localhost/v1/auth/oauth/twitter?project={project_id}&success=http://localhost/?success=1&failure=http://localhost/auth/signin?failure=2 
6) If successsful, you will be able to login back to appwrite console.
7) Then navigate to users. You should find your new user there. 
8) To verify that this user was added through twitter, You can open chrome dev tools > Network
9) Reload the page and look for a request like this 
test1213
10) Examine its payload to be 
test2
Except that Bitbucket should be replaced by twitter.
11) Test a failure as well and ensure that the user isn't added
If all goes well , update your PR and we'll get it merged

**Comment by eldadfux** [comment]
@ShivamRawat0l Are you still interested in working on this issue? We really want to release this feature with version 0.3.0

**Comment by ShivamRawat0l** [comment]
Sorry I am new to this and cannot understand some of the working of other code. You can assign the project to someone else I will try to do it locally.

**Pull request closed without merging**
