### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by friederbluemle**
A bunch of typo fixes (`Gitlab` -> `GitLab`, `Javascript` -> `JavaScript`, etc).

### CODE REVIEW

**Comment by friederbluemle** [comment]
@eldadfux - Please wait with the merge. I'm rebasing right now.

**Comment by friederbluemle** [comment]
Rebased onto latest `master` branch.

**Comment by eldadfux** [comment]
Let me know when you're ready 👌🏻

**Comment by friederbluemle** [comment]
@eldadfux - Thanks, ready to merge! 👍

**Comment by eldadfux** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on Gitter if you would like me to send you some cool Appwrite stickers and magnets!

**Pull request merged**
