### PR TITLE
feat: pass session to cloud function in oauth create sessions

### PR DESCRIPTION
**Pull request by christyjacob4**
## What does this PR do?

Pass the session object when creating an OAuth2 session

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)
Existing tests

## Related PRs and Issues

#1176 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
YES

### CODE REVIEW

**Comment by christyjacob4** [comment]
```
{
   "PATH":"/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
   "HOSTNAME":"3ee4b21f14e8",
   "APPWRITE_FUNCTION_ID":"60adf653c5aaa",
   "APPWRITE_FUNCTION_RUNTIME_VERSION":"3.9",
   "APPWRITE_FUNCTION_EVENT":"account.sessions.create",
   "APPWRITE_FUNCTION_DATA":"null",
   "APPWRITE_FUNCTION_PROJECT_ID":"60ad2999d4f41",
   "APPWRITE_FUNCTION_NAME":"test",
   "APPWRITE_FUNCTION_TAG":"60b0898d280c1",
   "APPWRITE_FUNCTION_TRIGGER":"event",
   "APPWRITE_FUNCTION_RUNTIME_NAME":"Python",
   "APPWRITE_FUNCTION_EVENT_DATA":"{\"$id\":\"\",\"userId\":\"60b08df467df8\",\"expire\":1653720576,\"provider\":\"discord\",\"providerUid\":\"433985911311695882\",\"providerToken\":\"***********\",\"ip\":\"172.18.0.1\",\"osCode\":\"MAC\",\"osName\":\"Mac\",\"osVersion\":\"10.15\",\"clientType\":\"browser\",\"clientCode\":\"CH\",\"clientName\":\"Chrome\",\"clientVersion\":\"90.0\",\"clientEngine\":\"Blink\",\"clientEngineVersion\":\"\",\"deviceName\":\"desktop\",\"deviceBrand\":\"Apple\",\"deviceModel\":\"\",\"countryCode\":\"--\",\"countryName\":\"\",\"current\":false}",
   "APPWRITE_FUNCTION_USER_ID":"null",
   "APPWRITE_FUNCTION_JWT":"null",
   "LANG":"C.UTF-8",
   "GPG_KEY":"*************",
   "PYTHON_VERSION":"3.9.2",
   "PYTHON_PIP_VERSION":"21.0.1",
   "PYTHON_GET_PIP_URL":"https://github.com/pypa/get-pip/raw/b60e2320d9e8d02348525bd74e871e466afdf77c/get-pip.py",
   "PYTHON_GET_PIP_SHA256":"c3b81e5d06371e135fb3156dc7d8fd6270735088428c4a9a5ec1f342e2024565",
   "PYTHONPATH":":/usr/local/src/.appwrite",
   "HOME":"/root"
}
```


Tested locally and it works 👍 

Just a question about the `current` attribute in the session.
In case of `createSession` endpoint, we are setting  `current = true`. 
In this case, do we need to go through all the sessions of the user, set the previously active session to false and set this current OAuth session to true?

**Review by TorstenDittmann — APPROVED** [review]

**Comment by alexweininger** [comment]
This is going to be great! 🔥🥳

**Comment by TorstenDittmann** [comment]
> In this case, do we need to go through all the sessions of the user, set the previously active session to false and set this current OAuth session to true?

iirc, the `current` attribute is not saved in the database and only added to the response 👍🏻

**Comment by eldadfux** [comment]
> > In this case, do we need to go through all the sessions of the user, set the previously active session to false and set this current OAuth session to true?
> 
> iirc, the `current` attribute is not saved in the database and only added to the response 👍🏻

I can confirm that `current` is not stored in the DB, no need for extra work.

**Review by eldadfux — APPROVED** [review]

**Pull request merged**
