### PR TITLE
Create fast2sms.php

### PR DESCRIPTION
**Pull request by garvitomer**
Added fast2sms (extensively used in India) service for phone provider.

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

### CODE REVIEW

**Review by eldadfux — CHANGES_REQUESTED** [review]
Hey @garvitomer thanks for contributing!

Did you get a chance to test the new adapter? If yes, please provide a proof that it works. Later the core team will make sure to add unit tests for this adapter with proper auth keys.

A few comments:
1. The file name should be: Fast2SMS.php.
2. You didn't initialize the new adapter as required here: https://github.com/appwrite/appwrite/blob/master/app/init.php#L996

Let me know if you have more questions. You can also reach the team on https://appwrite.io/discord

**Comment by garvitomer** [comment]
Hi, how to do the test can you please tell me the steps.
I will change the name and will add the adapter

**Comment by adityaoberai** [comment]
@garvitomer, if you need help initializing the phone auth adapter, you can look at https://github.com/appwrite/appwrite/pull/3540 as an example and add the details to `app/init.php` and `app/workers/messaging.php` accordingly.

After that is done, you can self-host this repository by following the instructions in the Contribution Guide [here](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md#setup-from-source).

Make sure to update the `.env` file in your cloned repo with the following

- `_APP_PHONE_PROVIDER=phone://<Account SID>:<Auth Token>@fast2sms`
- `_APP_PHONE_FROM=+14344251928` (the number should be your availed phone number from Fast2SMS

**Comment by adityaoberai** [comment]
@garvitomer please make the changes you've added in #3645 and #3646 in the same branch as the one here.

**Pull request closed without merging**
