### PR TITLE
DRAFT : Create OAuth session from a provided access token 

### PR DESCRIPTION
**Pull request by davidmartos96**
## Disclaimer 
I've never written a line of PHP code until now so I'm marking this as a draft and hopefully get some input on the feature. There may be things that I missed, but for what I tested it seems to work correctly.
Please let me know how can this be improved if needed.

## What does this PR do?

This PR includes a way to create an OAuth session by providing an Access token that gets fetched from the client.

## Test Plan

I've included a test that signs in with the mock token and then I tried signing in with a real Google access token from a Flutter application using the package `google_sign_in`.

## Related PRs and Issues

https://github.com/appwrite/appwrite/issues/879
https://github.com/appwrite/appwrite/issues/354

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

## Implementation
Mainly what I've done is move the logic from the oauth redirect method into a separate function that receives the access token. That function is called from a new method which I've called `/account/sessions/oauth2/:provider/from`

### CODE REVIEW

**Comment by eldadfux** [comment]
@davidmartos96 this looks nice, let me submit a couple of PRs to try and reduce the amount of code there, and try and help you avoid that function in the controller itself.

I might also try and create a forward method in the FW to allow us to better reuse the existing OAuth flow.

**Comment by davidmartos96** [comment]
@eldadfux Sounds great!

**Comment by eldadfux** [comment]
@davidmartos96 I'm merging this to a side-branch so we can keep doing some refactoring, hope to get this merged to 0.8 in a few days.

**Comment by davidmartos96** [comment]
@eldadfux Great! Thank you!

**Comment by hortigado** [comment]
Is there any news on this topic or an example of how to implement the `google_sign_in`. Thank you

**Comment by frendcarlo** [comment]
Hi, i'm looking forward on native google and apple signin for a non-profit organization, will this be in available in appwrite cloud?

**Pull request merged**
