### PR TITLE
Feat database indexing openapi fix

### PR DESCRIPTION
**Pull request by Meldiron**
## What does this PR do?

Swagger2 + OpenAPI3 support for new response models - multiple possible values for a type. For example `attributeList`.

## Test Plan

Swagger Editor didn't complain 😶

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

✅

### CODE REVIEW

**Review by TorstenDittmann — APPROVED** [review]

**Review by kodumbeats — CHANGES_REQUESTED** [review]
We'll also need to set `oneOf` as the response for a single attribute, but I couldn't find a good place to set that. Maybe `$model->getType()` could return a string for a single model or array for `oneOf?
https://github.com/appwrite/appwrite/blob/9c9a17a2a44ac06113e9ec54b1e9248425b16091/src/Appwrite/Utopia/Response/Model.php#L52-L57

**Comment by Meldiron** [comment]
> We'll also need to set `oneOf` as the response for a single attribute, but I couldn't find a good place to set that. Maybe `$model->getType()` could return a string for a single model or array for `oneOf?
> https://github.com/appwrite/appwrite/blob/9c9a17a2a44ac06113e9ec54b1e9248425b16091/src/Appwrite/Utopia/Response/Model.php#L52-L57


Sooo there is this definition of `anyOf`:
```
            ->addRule('attributes', [
                'type' => [
                    Response::MODEL_ATTRIBUTE_BOOLEAN,
                    Response::MODEL_ATTRIBUTE_INTEGER,
                    Response::MODEL_ATTRIBUTE_FLOAT,
                    Response::MODEL_ATTRIBUTE_EMAIL,
                    Response::MODEL_ATTRIBUTE_URL,
                    Response::MODEL_ATTRIBUTE_IP,
                    Response::MODEL_ATTRIBUTE_STRING // needs to be last, since its condition would dominate any other string attribute
                ],
                'description' => 'List of attributes.',
                'default' => [],
                'array' => true
            ])
```

Sooo `oneOf` would mean array in `type` but `array => false`, correct?  Sadly, there is no such usage in the code. But we can implement it 😊 Check it out: https://github.com/appwrite/appwrite/commit/c97b15325507b6eca319fca1fa38ab741be4e43a
(var_dump was removed in another commit)

**Comment by TorstenDittmann** [comment]
> Sooo `oneOf` would mean array in `type` but `array => false`, correct? Sadly, there is no such usage in the code. But we can implement it 😊 Check it out: [c97b153](https://github.com/appwrite/appwrite/commit/c97b15325507b6eca319fca1fa38ab741be4e43a)
> (var_dump was removed in another commit)

How do we distinguish between a response that will return only one Schema or one of many Schemas?

**Comment by Meldiron** [comment]
> > We'll also need to set `oneOf` as the response for a single attribute, but I couldn't find a good place to set that. Maybe `$model->getType()` could return a string for a single model or array for `oneOf?
> > https://github.com/appwrite/appwrite/blob/9c9a17a2a44ac06113e9ec54b1e9248425b16091/src/Appwrite/Utopia/Response/Model.php#L52-L57
> 
> Sooo there is this definition of `anyOf`:
> 
> ```
>             ->addRule('attributes', [
>                 'type' => [
>                     Response::MODEL_ATTRIBUTE_BOOLEAN,
>                     Response::MODEL_ATTRIBUTE_INTEGER,
>                     Response::MODEL_ATTRIBUTE_FLOAT,
>                     Response::MODEL_ATTRIBUTE_EMAIL,
>                     Response::MODEL_ATTRIBUTE_URL,
>                     Response::MODEL_ATTRIBUTE_IP,
>                     Response::MODEL_ATTRIBUTE_STRING // needs to be last, since its condition would dominate any other string attribute
>                 ],
>                 'description' => 'List of attributes.',
>                 'default' => [],
>                 'array' => true
>             ])
> ```
> 
> Sooo `oneOf` would mean array in `type` but `array => false`, correct? Sadly, there is no such usage in the code. But we can implement it 😊 Check it out: [c97b153](https://github.com/appwrite/appwrite/commit/c97b15325507b6eca319fca1fa38ab741be4e43a)
> (var_dump was removed in another commit)

The problem with this is it only solved the problem of nested components. We still didn't solve root components that could be oneOf.

To solve this, we need to add support for array parameter into `->label('sdk.response.model', Response::MODEL_EXECUTION)`

**Comment by Meldiron** [comment]
I set `createExecution` response to `->label('sdk.response.model', [Response::MODEL_EXECUTION, Response::MODEL_ATTRIBUTE])` for testing purposes. Swagger definition looks like:

image


```
        "responses": {
          "201": {
            "description": "Execution, or Attribute",
            "content": {
              "application/json": {
                "schema": {
                  "oneOf": [
                    {
                      "$ref": "#/components/schemas/execution"
                    },
                    {
                      "$ref": "#/components/schemas/attribute"
                    }
                  ]
                }
              }
            }
          }
        },
```

The rest of the document was valid.

**Review by kodumbeats — APPROVED** [review]

**Pull request merged**
