### PR TITLE
Translated into marathi -mr

### PR DESCRIPTION
**Pull request by spielers**
hey, I have translated into Marathi language and  created a pull request to the 0.7.x branch please review and merge it

### CODE REVIEW

**Comment by spielers** [comment]
@eldadfux let's get this merged I will take another issue then.:)

**Comment by eldadfux** [comment]
Cool, just waited for tests to pass before I can review manually.

**Comment by spielers** [comment]
cool!

**Comment by spielers** [comment]
@eldadfux Thank you Very Much, It was my First PR ;)

**Pull request merged**
