### PR TITLE
Optimize images

### PR DESCRIPTION
**Pull request by JeffResc**
## What does this PR do?

This pull request optimizes the images found in the repository using lossless compression. This means that the image quality will not be degraded. This will mean less space taken up by images along with faster loading times when viewing them. The overall file size has been reduced by around 20%.

## Test Plan

N/A, no code was changed.

## Related PRs and Issues

N/A, no associated issues or PRs.

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by eldadfux** [comment]
Hey @JeffResc, thanks for submitting the PR. Please note, some tests are failing. I guess this is because you have also optimized some images we only use as resources for testing, and we're also checking their size to validate the image manipulation APIs are working properly.

**Comment by JeffResc** [comment]
Thanks for the review @eldadfux. Should I go ahead and modify those tests to make them the correct size?

**Comment by eldadfux** [comment]
Yes please 🙏🏻

**Comment by JeffResc** [comment]
@eldadfux Looks like I'm unable to run the tests in Docker. I ran `docker-compose up -d`, but the appwrite_appwrite wouldn't come up due to the following error:
```
/usr/local/bin/start: line 2: $'\r': command not found

/usr/local/bin/start: line 4: $'\r': command not found

/usr/local/bin/start: line 6: $'\r': command not found

/usr/local/bin/start: line 8: $'\r': command not found

/usr/local/bin/start: line 10: syntax error near unexpected token `$'{\r''

'usr/local/bin/start: line 10: `function setEnvironmentVariable() {
```

**Comment by eldadfux** [comment]
Try to switch to branch `0.7.x` and then run `docker-compose build && docker-compose up -d` after that run the tests with `docker-compose exec appwrite test`

**Comment by JeffResc** [comment]
@eldadfux Yes that works, should I go ahead and change this PR to use that as the target branch?

**Comment by eldadfux** [comment]
Yes 👍🏻

**Comment by JeffResc** [comment]
@eldadfux Whoops, I guess I spoke too soon. Thought it was working, but same error on the 0.7.x branch. Are there any known issues with running appwrite in the WSL backend for Docker?

**Comment by eldadfux** [comment]
Windows can always be a problem when it comes to Docker. Can you try and run it on a UNIX VM? Let me know if you still have issues, if yes I can try and fix the tests on your branch.

**Comment by SoftCreatR** [comment]
@eldadfux 

Maybe use https://github.com/apps/imgbot instead to automate this task even in the future.

**Comment by eldadfux** [comment]
> @eldadfux
> 
> Maybe use https://github.com/apps/imgbot instead to automate this task even in the future.

I'll give it a look 👌🏻

**Comment by SoftCreatR** [comment]
> > @eldadfux
> > Maybe use https://github.com/apps/imgbot instead to automate this task even in the future.
> 
> I'll give it a look 👌🏻

All you need is a `.imgbotconfig` containing a list of files to ignore. This way, you can prevent your tests from breaking and only compress/optimize relevant files.

**Pull request closed without merging**
