### PR TITLE
Removed redundant commas

### PR DESCRIPTION
**Pull request by jgentes**
## What does this PR do?

Addresses https://github.com/appwrite/appwrite/issues/7606

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Screenshots may also be helpful.)

## Related PRs and Issues

- (Related PR or issue)

## Checklist

- [ ] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [ ] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

### CODE REVIEW

**Comment by stnguyen90** [comment]
@jgentes, are you able to trigger one email and share a screenshot?

**Comment by jgentes** [comment]
Sure: 
image

**Comment by jgentes** [comment]
Also what's interesting is that I was *not* able to find the *English* version of the template, so while I fixed all other languages, I'm not sure this will actually fix the issue for me!

**Review by stnguyen90 — CHANGES_REQUESTED** [review]
> Sure: image

Thanks, but this shows the problem. I was asking for a screenshot of the fix applied to verify the change worked.

> Also what's interesting is that I was not able to find the English version of the template, so while I fixed all other languages, I'm not sure this will actually fix the issue for me!

The english one is [here](https://github.com/appwrite/appwrite/blob/main/app/config/locale/translations/en.json). This was fixed in 1.5, but Cloud is still on 1.4.

**Comment by jgentes** [comment]
I see, I don't have it running locally so I don't have a screenshot. I may have time to get it setup this weekend, not sure. I was just looking for the english fix anyway :)

**Review by stnguyen90 — APPROVED** [review]
LGTM

image

**Pull request merged**
