### PR TITLE
Add Tradeshift OAuth2 provider for live and sandbox

### PR DESCRIPTION
**Pull request by armino-dev**
## What does this PR do?

This PR adds the Tradeshift OAuth2 providers for production and sandbox environments, which will be useful for business-oriented users.

## Test Plan

Code was verified using JS API.

## Related PRs and Issues

This PR is related to #410.

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Review by TorstenDittmann — CHANGES_REQUESTED** [review]
Thanks for your PR 👋🏻 

I see some whitespace inconsistencies mixing up tabs and spaces. Could you adjust them to 4 spaces? 🙂

**Comment by armino-dev** [comment]
> Thanks for your PR 👋🏻
> 
> I see some whitespace inconsistencies mixing up tabs and spaces. Could you adjust them to 4 spaces? 🙂

Fixed 🔧 .

**Review by TorstenDittmann — APPROVED** [review]
lgtm 👍🏻 

@eldadfux mind taking a look?

**Comment by eldadfux** [comment]
Awesome as always! @armino-dev

**Pull request merged**
