### PR TITLE
Grammar fixes

### PR DESCRIPTION
**Pull request by DenverCoder1**
Removed colon and added commas to separate list elements

### CODE REVIEW

**Review by king-11 — COMMENTED** [review]
@DenverCoder1 thanks for your contribution but you could have just added them to the second pr that you created and focused on some more prominent issue, that you can look up the issues tab .That would really help the project if you wish to contribute.

**Comment by DenverCoder1** [comment]
> you could have just added them to the second pr that you created

Thanks, is there anything I can do about that now or should I just leave it as is?

**Comment by king-11** [comment]
push those changes to the same branch as the later one it will be added to your pr

**Comment by DenverCoder1** [comment]
> push these changes to the same branch as the later one it will be added to your pr

Done, thanks! These changes were pushed to #579.

**Comment by king-11** [comment]
@DenverCoder1 thanks it is a good practice as saves time of maintainers and yeah thanks for your contribution :)

**Pull request closed without merging**
