### PR TITLE
Feat Root Account

### PR DESCRIPTION
**Pull request by eldadfux**
## What does this PR do?

Added an option to limit the console to one god account. This will allow only to one user to register to the Appwrite console. When a user has already signed-up the console account creation endpoint will be blocked. Added some updates to the UI to reflect the changes when this mode is on. From the next Appwrite version this feature is going to enabled by default.

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

#472 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes.

### CODE REVIEW

**Comment by eldadfux** [comment]
Auth UI when GOD mode is enabled:

localhost_auth_recovery
localhost_auth_signin
localhost_auth_signup (1)

Auth UI when god is disabled:
image

**Comment by eldadfux** [comment]
@TorstenDittmann its important that we don't release this feature before we provide a way to disable anon login.

**Review by lohanidamodar — APPROVED** [review]
LGTM

**Review by TorstenDittmann — APPROVED** [review]
lgtm 👍🏻

**Review by kodumbeats — APPROVED** [review]

**Pull request merged**
