### PR TITLE
Translation in Punjabi#HacktoberFest  :)

### PR DESCRIPTION
**Pull request by Priyanka788**

### CODE REVIEW

**Comment by eldadfux** [comment]
Hey @Priyanka788, to be able to merge this locale we need translation for both the settings and the email templates as listed below:

Email Templates
app/config/locales/templates/en.email.auth.confirm.tpl
app/config/locales/templates/en.email.auth.invitation.tpl
app/config/locales/templates/en.email.auth.recovery.tpl

Thanks!

**Comment by Priyanka788** [comment]
If there is any other mistake please send me a message

**Comment by eldadfux** [comment]
THANK YOU @Priyanka788! All changes merged 🥳 

Please reach out to me on our [Discord server](https://discord.gg/GSeTUeA) if you would like me to send you some cool Appwrite stickers and magnets!

To say thank you, we have just invited you to join the Appwrite organization on GitHub. Accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership visibility settings, so your new Appwrite team membership will show up on your personal GitHub profile.

**Comment by eldadfux** [comment]
This PR will be deprecated in version 0.7 do to a lot of mistakes and unrelated comments in the translations.

**Pull request merged**
