### PR TITLE
typo fixes in README.md

### PR DESCRIPTION
**Pull request by Parikshit-Hooda**
Fixed typos.
   repititve -> repititive
   'hosts ' -> 'hosts, '
    getting started -> Getting Started
    signin -> sign-in
    commuinty -> community

### CODE REVIEW

**Comment by eldadfux** [comment]
Hey @Parikshit-Hooda, we got multiple PRs on the README file, please resolve the conflicts before I can merge

**Comment by Parikshit-Hooda** [comment]
@eldadfux  done.

**Comment by eldadfux** [comment]
All merged! 🥳

@Parikshit-Hooda please reach out on Gitter if you would like me to send you some Appwrite stickers and magnets!

**Comment by Parikshit-Hooda** [comment]
okay @eldadfux

**Pull request merged**
