### PR TITLE
Show Stdout with build logs when build fails

### PR DESCRIPTION
**Pull request by PineappleIOnic**
## What does this PR do?

This PR will make it so the logs popup box for function builds will display stdout aswell as stderr when a build fails

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
Yes, I have

### CODE REVIEW

**Review by Meldiron — CHANGES_REQUESTED** [review]
__Manual QA__

1. I can see `logs` when its building. It indicates I would see realtine data, which I don't (its empty). Can we hide it?
2. When finished and output is empty, language on right side is missplaced. Can we solve this? Maybe a task for Elad? If not, can we say `No logs` so it looks better?

CleanShot 2022-03-22 at 09 12 41@2x
CleanShot 2022-03-22 at 09 13 14@2x

**Comment by TorstenDittmann** [comment]
> **Manual QA**
> 
> 1. I can see `logs` when its building. It indicates I would see realtine data, which I don't (its empty). Can we hide it?
> 2. When finished and output is empty, language on right side is missplaced. Can we solve this? Maybe a task for Elad? If not, can we say `No logs` so it looks better?
> 
> CleanShot 2022-03-22 at 09 12 41@2x
> 
> CleanShot 2022-03-22 at 09 13 14@2x

If no logs, we should show `No Logs` 👍🏻

**Review by christyjacob4 — APPROVED** [review]

**Comment by christyjacob4** [comment]
@PineappleIOnic Can you attach a screenshot of what it looks like now ?

**Comment by PineappleIOnic** [comment]
image

**Comment by eldadfux** [comment]
> image

Would it make more sense to change the labels to stdout and stderr?

**Comment by eldadfux** [comment]
Also, how does the UI look when both logs have a lot of data?

**Comment by PineappleIOnic** [comment]
It currently doesn't look the best, we may need to add a max-height with a auto scroll y
image

**Comment by PineappleIOnic** [comment]
I've implemented your suggestions, logs now look like this:
image

**Review by eldadfux — APPROVED** [review]
@christyjacob4 I added this to manual QA so we get more hands testing the new components when having long logs.

**Comment by eldadfux** [comment]
Not relevant due to the new console.

**Pull request closed without merging**
