### PR TITLE
Feat-1764-telugu translation

### PR DESCRIPTION
**Pull request by Ln11211**
## What does this PR do?

**This PR closes this issue #1764 .**
Tasks summary:
- [x] Fork & clone Appwrite
- [x]  Generate translations for Telugu in app/config/locale/translations/te.json
- [x]  Add language as supported into app/config/locale/codes.php, if not already presented
- [x]  Add language as supported into app/init.php, if not already presented
- [x]  Test the translations
- [x]  Push changes and submit a pull request

**I have taken permission to work on this issue and raise a PR in Discord.**

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)
**NONE**
### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
**yes. I did.**

### CODE REVIEW

**Comment by Ln11211** [comment]
@Meldiron & @lohanidamodar , can you please review my PR and let me know if I have to add any more translations..
I was not assigned this task but I have requested @melidron to work on this in the discord server and even informed that I have worked on this and raised a PR in the server.

**Comment by Ln11211** [comment]
@Meldiron , Sorry to ping again but can you please review this PR ?

**Comment by Ln11211** [comment]
@lohanidamodar, I'm sorry that I keep mentioning you here, but can you please review this PR ?

**Comment by Ln11211** [comment]
@christyjacob4 , If you have some time, can you please review and merge this?

**Review by christyjacob4 — APPROVED** [review]

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)

**Pull request merged**
