### PR TITLE
FIX-7880-added-HongKong-to-countries.php

### LINKED ISSUE #7880: 🐛 Bug Report: Location does not seem to be compatible with the Chinese region
### 👟 Reproduction steps

Access using IP of [China-Hong Kong], shows unknown

### 👍 Expected behavior

The Location field displays [China Hong Kong]

### 👎 Actual Behavior

image

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

[Version 1.5.3](https://github.com/appwrite/appwrite/releases)
Using console operations and Kotlin SDK 5.0.1

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by deanurag**
Fixes #7880 
## What does this PR do?

This PR has added Hong Kong to the Countries Database. 

## Changes
HongKong

## Checklist

- [x] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [x] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

### CODE REVIEW

**Review by stnguyen90 — CHANGES_REQUESTED** [review]
Looks like some tests require updating. Would you please take a look?

**Comment by deanurag** [comment]
> Looks like some tests require updating. Would you please take a look?

I am not able to understand, why the GraphQL and locale tests are failing, can you share some insight about it?

**Comment by stnguyen90** [comment]
> I am not able to understand, why the GraphQL and locale tests are failing, can you share some insight about it?

@deanurag, if you look at the test output, you'll see the file and line for the failed test. For example, the [graphql test](https://github.com/appwrite/appwrite/actions/runs/8656927294/job/23833884967?pr=7962) says:

```
There were 10 failures:

1) Tests\E2E\Services\GraphQL\BatchTest::testArrayBatchedQueries
Failed asserting that 196 matches expected 195.

/usr/src/code/tests/e2e/Services/GraphQL/BatchTest.php:36
/usr/src/code/tests/extensions/Retryable.php:26

...
```

If you look at that that file (tests/e2e/Services/GraphQL/BatchTest.php) and line (36), you'll see where it failed:

https://github.com/appwrite/appwrite/blob/505637d1190881d131fbe2eb003e6b27676a4387/tests/e2e/Services/GraphQL/BatchTest.php#L36

**Comment by deanurag** [comment]
I have done the changes  can you please take a look

**Review by stnguyen90 — CHANGES_REQUESTED** [review]
There are still some failed tests.

**Comment by deanurag** [comment]
Please do check now, i have done the necessary changes.

**Comment by deanurag** [comment]
Please check the changes.

**Review by stnguyen90 — APPROVED** [review]

**Comment by stnguyen90** [comment]
Hey 👋 awesome work on your PR!

**Pull request merged**
