### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by Kolkies**

### CODE REVIEW

**Comment by Kolkies** [comment]
The countries are almost done, after that everything is translated

**Comment by eldadfux** [comment]
Great job! Let me know when it's ready to be reviewed... 👍🏻

**Comment by Kolkies** [comment]
@eldadfux ready for the review

**Comment by eldadfux** [comment]
@Kolkies Thank you so much! All changes merged 🥳

Please reach out to me on Gitter if you would like me to send you some cool Appwrite stickers and magnets!

**Pull request merged**
