### PR TITLE
correct the wrong translation in indonesian

### PR DESCRIPTION
**Pull request by fadila-amin**
I changed incorrect translation to correct (wikipedia bassed).

### CODE REVIEW

**Comment by spielers** [comment]
@fadila-amin Thanks For your contributions. I would like you to make PR to 0.7.x  branch !

Best,
spielers

**Comment by fadila-amin** [comment]
i am verry sorry about that. how to fix this?

**Comment by spielers** [comment]
Hey, @fadila-amin you can change your working directory in your local machine.set current working directory to 0.7.x and do changes there and make PR from that branch,

best,
spielers

**Comment by spielers** [comment]
Hey, @fadila-amin let me know are you still working on this. ping me if any help needed 

best,
spielers

**Comment by fadila-amin** [comment]
> Hey, @fadila-amin let me know are you still working on this. ping me if any help needed
> 
> best,
> spielers

hai @spielers, i hope you can let me try again.

**Pull request closed without merging**
