### PR TITLE
Update Malayalam translations

### PR DESCRIPTION
**Pull request by anoopmsivadas**
## What does this PR do?

Updates Malayalam translations in ```ml.json```.

## Test Plan

Used the glossary of Microsoft and Mozilla for cross checking the words I used for translation. The tranlated strings are based on the English translations from en.json. And also have run the e2e testcases for Locale.

## Related PRs and Issues

#1702 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

yes

### CODE REVIEW

**Review by christyjacob4 — CHANGES_REQUESTED** [review]
Please address the comments

**Comment by anoopmsivadas** [comment]
> Please address the comments

Hey @christyjacob4 , I have fixed the issues mention. Please review at your convenience. Thanks

**Comment by christyjacob4** [comment]
Awesome . Looks great :+1:

**Review by christyjacob4 — APPROVED** [review]

**Comment by christyjacob4** [comment]
THANK YOU so much! All changes merged 🥳
Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swag!

**Pull request merged**
