### PR TITLE
Updated password length min requirment in the console

### PR DESCRIPTION
**Pull request by eldadfux**
## What does this PR do?

Updated the console validations to match #2439 

## Test Plan

N/A

## Related PRs and Issues

#2439 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes.

### CODE REVIEW

**Comment by TorstenDittmann** [comment]
We might wanna use the `minlength` attribute here instead of `pattern`. This will also trigger the proper event to the browser => https://developer.mozilla.org/en-US/docs/Web/API/ValidityState/tooShort

Which then will give native a11y notes from the browser to the user 👍🏻

**Review by kodumbeats — APPROVED** [review]
I'm not up-to-speed on the difference between `pattern` and `minlength`, so I defer to y'all there. If we do change that, let's remember to change the other form from https://github.com/appwrite/appwrite/pull/2439:
https://github.com/appwrite/appwrite/blob/61ffe18d2b229b788e4194abf8ba47768f83d63b/app/views/home/auth/signup.phtml#L48

Otherwise, LTGM 👍🏻

**Comment by TorstenDittmann** [comment]
> I'm not up-to-speed on the difference between `pattern` and `minlength`, so I defer to y'all there. If we do change that, let's remember to change the other form from #2439:
> 
> https://github.com/appwrite/appwrite/blob/61ffe18d2b229b788e4194abf8ba47768f83d63b/app/views/home/auth/signup.phtml#L48
> 
> Otherwise, LTGM 👍🏻

https://svelte.dev/repl/3d6730a47fd643299cbd74b9bde9e0f9?version=3.46.2

Try entering less than 8 chars and you will get a proper note whats wrong in terms of length 👍🏻

**Comment by kodumbeats** [comment]
> https://svelte.dev/repl/3d6730a47fd643299cbd74b9bde9e0f9?version=3.46.2
> 
> Try entering less than 8 chars and you will get a proper note whats wrong in terms of length 👍🏻

Ah, I see. I guess the browser doesn't have a friendly way to decode the pattern. Looks clean

**Pull request merged**
