### PR TITLE
Remove invalid link

### PR DESCRIPTION
**Pull request by kalpeshT101**
## What does this PR do?

Removed invalid link from readme

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

### CODE REVIEW

**Comment by vrabe** [comment]
Removing is not the best. You can make it valid!

**Comment by gewenyu99** [comment]
What @vrabe said! XD Good catch though!

**Comment by vrabe** [comment]
Facebook 群组 means Facebook group. So there should be the link of Facebook group.

**Comment by kalpeshT101** [comment]
@gewenyu99  @vrabe

**Comment by gewenyu99** [comment]
@kalpeshT101 please keep using `、` instead of `,` for consistency. Chinese punctuations are different from English ones.

**Comment by PineappleIOnic** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Review by gewenyu99 — APPROVED** [review]
Great! Thank you for this PR ❤️ 

LGTM

**Review by christyjacob4 — APPROVED** [review]

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

**Pull request merged**
