### PR TITLE
Added Yammer OAuth2 Provider

### PR DESCRIPTION
**Pull request by AmreshSinha**
## What does this PR do?

Added Yammer OAuth2 Provider :blush: 

## Test Plan

I used
https://github.com/AmreshSinha/OAuth-Tester-Appwrite
to test the new Provider

Here is a Screenshot of successful Login:
image

## Related PRs and Issues

#1781 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes :blush:

### CODE REVIEW

**Review by christyjacob4 — CHANGES_REQUESTED** [review]
Looks great! Can you share a gif / video of the OAuth login flow so that we can verify this quickly ? 

In the users page on the Appwrite console, please open the network tab and share the response of the call to GET /users/ 

I'd also like you to confirm that the icon is 100x100px i size and is of a good quality. 
At present, the Yammer logo appears a bit pixelated.

**Comment by AmreshSinha** [comment]
I have sent the video over Discord.

Icon is fo 100x100 size and the original file was taken from their site only.

**Review by christyjacob4 — APPROVED** [review]
This looks great! Amazing work!

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged :partying_face:

Please reach out to me on discord to claim your hacktoberfest swag! 

As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord so that we can add you as a contributor to our organization.

Once added, you can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite membership badge will show up on your personal GitHub profile.

**Pull request merged**
