### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by jakaya123**
Done a simple alignment change and I have included the link for appwrite's official blog.

## What does this PR do?

 A simple alignment change and included the link for appwrite's official blog.

## Test Plan

Only the content and quality of the content is improved.

## Related PRs and Issues

_

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues]

Yes

### CODE REVIEW

**Comment by spielers** [comment]
Hey, @jakaya123 thanks for your contributions.

best,
Spielers

**Comment by eldadfux** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like me to send you some cool Appwrite stickers and magnets! Please note that shipping might take longer times because of COVID19.

As a way of saying thank you, we have just invited you to join the Appwrite organization on GitHub. You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

**Comment by jakaya123** [comment]
Hi Eldad,
I would like to receive some stickers.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by rjn01** [comment]
Hi Jakaya,
He would surely send the Appwrite swags, it would be getting late due to COVID-19 pandemic.
Even i am waiting for the swags.
Mean while, you can follow Appwrite on twitter to check if they are dispached or not.

**Comment by jakaya123** [comment]
Ok thanks for your reply.

**Pull request merged**
