### PR TITLE
Added Shona Translations

### PR DESCRIPTION
**Pull request by TafadzwaD**
## What does this PR do?

Provides Shona Translations To AppWrite

## Test Plan
 The test plan is provided on the following link [https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md#4-test-the-translations]()

## Related PRs and Issues

The Pull Request resolves this issue #2006

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by christyjacob4** [comment]
Some minor changes :+1:

**Comment by christyjacob4** [comment]
@TafadzwaD  closing this PR for now since there has been no activity in quite a long time. Feel free to reopen it when you're ready to start working on it once again. 🙂

**Comment by TafadzwaD** [comment]
@christyjacob4 kindly reopen for me.. Seems like I can do so from my end.. I'm ready to commit the suggested changes

**Review by christyjacob4 — APPROVED** [review]

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged :partying_face:

Please reach out to me on Discord to claim your hacktoberfest swag! 

As a way of saying thank you, we would also love to invite you to join the Appwrite organisation on GitHub. Please share your GitHub username with us on Discord so that we can add you as a contributor to our organisation.

Once added, you can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite membership badge will show up on your personal GitHub profile.

**Pull request merged**
