### PR TITLE
Fix + improve permissions UI

### PR DESCRIPTION
**Pull request by abnegate**
## What does this PR do?

- Fix resetting permissions matrix after creating a file
- Fix file update permissions matrix display issues
- Ensure add row events are only listened to by local components
- Disallow multiple rows with the same role
- Disallow rows with no permissions set
- Widen file update modal to better fit permissions view

## Test Plan

Existing tests

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by abnegate** [comment]
Screen Shot 2022-08-30 at 12 10 45 AM
Screen Shot 2022-08-30 at 12 10 17 AM
Screen Shot 2022-08-30 at 12 09 38 AM
Screen Shot 2022-08-30 at 12 08 40 AM
Screen Shot 2022-08-30 at 12 08 03 AM
Screen Shot 2022-08-30 at 12 07 19 AM

**Review by lohanidamodar — CHANGES_REQUESTED** [review]
The screenshots look mostly good. Can we have some mobile screenshots so we can be sure mobile version looks good enough?

**Comment by abnegate** [comment]
@lohanidamodar All looks pretty bad on mobile. Usable everywhere except the update file modal. Not sure why it's different there. Any ideas?

Screen Shot 2022-08-30 at 9 55 40 PM
Screen Shot 2022-08-30 at 9 54 58 PM
Screen Shot 2022-08-30 at 9 55 12 PM
Screen Shot 2022-08-30 at 9 54 04 PM
Screen Shot 2022-08-30 at 9 55 55 PM
Screen Shot 2022-08-30 at 9 56 33 PM

**Review by Haimantika — APPROVED** [review]
Looks good 👍

**Pull request merged**
