### PR TITLE
Typo Fixes + Fixing Grammatical errors

### PR DESCRIPTION
**Pull request by KaranSinghBisht**
Added at before the email address as its more grammatically correct

### CODE REVIEW

**Review by srinath1412001 — COMMENTED** [review]
hacktoberfest

**Comment by KaranSinghBisht** [comment]
@srinath1412001 
I'm not doing it for the 4 pr....

**Comment by spielers** [comment]
Hey, @KaranSinghBisht  Thanks for your contribution But this PR is not a valid PR considering the rules of Hacktoberfest. I would you should have a look at our open issues #25 #546 
 
Best,
spielers

**Comment by lukeocodes** [comment]
Just my 2c.

This is not the correct use of `invalid` and neither are many of your `invalid` tags on this repository. `invalid` and `spam` can have users disqualified from Hacktoberfest. 

If a PR is made in good faith, (like this one is - fixing genuine typos,) but you don't want to merge it, then simply close the PR.

If a PR is a lot of effort, but cannot be merged, (like some others,) then simply close the PR and add the `hacktoberfest-accepted` label.

If you don't intend on correctly applying the labels, perhaps remove the `hacktoberfest` topic from your repository.

[Hacktoberfest reducing spam details](https://hacktoberfest.digitalocean.com/details#spam)

**Comment by div-bargali** [comment]
I agree with @lukeocodes . This is rude. Simply closed the PR, if you are not ready to merge it. Adding `invalid` tag to valid fixes even if it's just 1 line change makes no sense.

**Comment by spielers** [comment]
Hey, everyone I strongly apologize for our side. I had a discussion with @eldadfux  we are following the guideline of  Hacktoberfest will merge the Potential PRs including this one. I know and understand how much time required to create a PR for the First time we also been through the same. but just changing a word or adding small indefinite articles won't be counted regarding hacktoberfest rules. we all are following rules and helping new contributors to contribute for the first time but avoiding spam and repeated PR's we have to add an invalid tag on some PR please bare with us will get the potential PR merged asap

best,
spielers

**Comment by eldadfux** [comment]
Hey all, Apologies from our side.

It seems like we have misused the `invalid` label for a few times now while trying to follow hacktoberfest guidelines incorrectly.

We have asked our team to stop using that label, but for extreme abuse cases, and only after a team discussion on such issues had been taken.

We will re-review all the labels that have been applied recently. Appwrite has a commitment to support open-source contributions for both beginners and seniors alike, and we want to make sure our community is as welcoming as possible. 

We'll fix the mistakes that have been made. Thank you for your feedback.

**Comment by eldadfux** [comment]
Going back to the original topic, @KaranSinghBisht Thanks for the PR.

This PR is entitled to Appwrite free SWAG package (1 merged PR). Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like me to send you some cool Appwrite stickers and magnets! Please note that shipping might take longer times because of COVID19.

As a way of saying thank you to any of our contributors, we are inviting code contributors to join the Appwrite organization on GitHub. You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

**Comment by KaranSinghBisht** [comment]
@eldadfux Thank you so much!

**Pull request merged**
