### PR TITLE
Fixed appwrite/docs/examples/javascript/auth files

### PR DESCRIPTION
**Pull request by avijit1998**

### CODE REVIEW

**Comment by avijit1998** [comment]
Fixed login.md, oauth.md, register.md

**Review by king-11 — COMMENTED** [review]
would love to know what was fixed @avijit1998

**Comment by avijit1998** [comment]
Yes, those readme files were in plain text, I formatted them

**Comment by eldadfux** [comment]
@avijit1998 this files are used to auto-generate docs on https://appwrite.io. No markdown format is needed. We would love you help with other open issues.

**Pull request closed without merging**
