### PR TITLE
modify swoole buffer output size

### PR DESCRIPTION
**Pull request by lohanidamodar**
## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

### CODE REVIEW

**Comment by eldadfux** [comment]
Does solve the file download issues?

**Comment by lohanidamodar** [comment]
I've verified with bunch of different File sizes and types, seems to work. One issue though, the files uploaded before the Fix are being downloaded correctly.

**Comment by eldadfux** [comment]
> I've verified with bunch of different File sizes and types, seems to work. One issue though, the files uploaded before the Fix are being downloaded correctly.

Are being download correctly or not?

**Comment by lohanidamodar** [comment]
> > I've verified with bunch of different File sizes and types, seems to work. One issue though, the files uploaded before the Fix are being downloaded correctly.
> 
> Are being download correctly or not?

Hehe, honest mistake, was not being downloaded correctly. However, it was browser cache issue. So Safe to say it's resolved

**Pull request merged**
