### PR TITLE
Fix docs showing endpoint for client

### PR DESCRIPTION
**Pull request by Meldiron**
## What does this PR do?

- Fix bug when docs were showing `Retry Build` to the client
- Re-ordered endpoints. First entity, then action (create,list,get,update,delete). Action from least detailed to the most
- Renamed some endpoint descriptions to make them more consistent
- Fix some types, so homepage doesn't fail to start

## Test Plan

- [x] Test with homepage repo. Screenshots are provided as a comment on this PR

## Related PRs and Issues

x

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes 😇

### CODE REVIEW

**Comment by Meldiron** [comment]
Screenshots:

CleanShot 2022-06-07 at 10 06 53@2x


CleanShot 2022-06-07 at 10 06 37@2x

CleanShot 2022-06-07 at 10 06 31@2x


CleanShot 2022-06-07 at 10 06 19@2x

CleanShot 2022-06-07 at 10 05 49@2x

CleanShot 2022-06-07 at 10 05 32@2x

CleanShot 2022-06-07 at 10 05 23@2x


CleanShot 2022-06-07 at 10 08 34@2x


CleanShot 2022-06-07 at 10 08 30@2x

**Comment by TorstenDittmann** [comment]
The diff makes it super hard to review, will take some time 😁

**Comment by stnguyen90** [comment]
@Meldiron And now there are merge conflicts. Perhaps it's possible to break down this PR?

**Comment by eldadfux** [comment]
We have a lot of naming inconsistencies when creating a session. Also, email shouldn't be treated as the default way.

**Comment by christyjacob4** [comment]
Ensure we fix the naming convention of the **Create Account Session** endpoints
1. Create Email Session 
2. Create Phone Session 
3. Create Anonymous session etc.

**Comment by PineappleIOnic** [comment]
Due to the merge conflicts,  #3667 has been created to supplant this PR.

**Comment by christyjacob4** [comment]
closing this in favour of #3667

**Pull request closed without merging**
