### PR TITLE
The continents.php in Gujarati issue#25

### PR DESCRIPTION
**Pull request by EricBrianAnil**
Added the local Malayalam translation to continents.php

### CODE REVIEW

**Comment by EricBrianAnil** [comment]
Added continents.php Malayalam translation as to enhance the repo as per mentioned in issue #25

**Comment by eldadfux** [comment]
https://github.com/appwrite/appwrite/pull/212 there is already a pending PR with this translation.

**Comment by EricBrianAnil** [comment]
added new pr with gujarati language

**Comment by eldadfux** [comment]
Hey @EricBrianAnil  This PR has only one translations file from 6 required to add a new locale.

**Comment by eldadfux** [comment]
Hey @EricBrianAnil are still on this?

**Pull request closed without merging**
