### PR TITLE
feat(locale): add zh-tw

### PR DESCRIPTION
**Pull request by haktober**
## Description
Adds `zh-tw` to list of locales.

### CODE REVIEW

**Comment by eldadfux** [comment]
Just to make sure, what is our current zh locale?

zh-CN, zh-TW or zh-HK?

**Comment by haktober** [comment]
zh-CN @eldadfux

**Comment by eldadfux** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on Gitter if you would like me to send you some cool Appwrite stickers and magnets!

**Comment by haktober** [comment]
very cool!

**Pull request merged**
