### PR TITLE
Swoole and functions adapter/database / src/Appwrite/Database/Adapter.php

### PR DESCRIPTION
**Pull request by ramadh-an**
@@ -68,7 +68,7 @@ public function getNamespace()
     *
     * @return array
     */
    abstract public function createDocument(array $data, array $unique);
    abstract public function createDocument(array $data = [], array $unique = []);

    /**
     * Update Document.
@@ -77,7 +77,7 @@ public function getNamespace()
     *
     * @return array
     */
    abstract public function updateDocument(array $data);
    abstract public function updateDocument(array $data = []);

    /**
     * Delete Node.

### CODE REVIEW

**Comment by eldadfux** [comment]
@ramadh-an are you sure you're submitting the changes against the correct branch? This PR has 731 changes.

**Comment by ramadh-an** [comment]
yes im sure,

Pada tanggal Kam, 1 Okt 2020 pukul 11.54 Eldad A. Fux <
notifications@github.com> menulis:

**Comment by eldadfux** [comment]
And what exactly is this PR about?

It seems like you're just merging our dev branch which is not production ready into our master branch

**Comment by ramadh-an** [comment]
about fixed appwrite database,correct me if im  wrong,

Pada tanggal Kam, 1 Okt 2020 pukul 12.05 Eldad A. Fux <
notifications@github.com> menulis:

**Comment by eldadfux** [comment]
This does not seem valid. Please submit a new PR with only the changes you need to make. If you need help getting started you can reach out to our #mainatiners channel on https://appwrite.io/discord.

**Pull request closed without merging**
