### PR TITLE
Add unknown image

### PR DESCRIPTION
**Pull request by PineappleIOnic**
+ Unknown Image when User-Agent can't be found
+ Added 'Unknown' text when User-Agent can't be found

### CODE REVIEW

**Comment by eldadfux** [comment]
@PineappleIOnic, could you add the same fix in the /console/account/devices url?
image

**Comment by PineappleIOnic** [comment]
Will do

**Comment by PineappleIOnic** [comment]
The above should fix it, need to quickly fire up a development server on my other computer to check that everything is all functional. 👍

**Comment by PineappleIOnic** [comment]
Everything looks all a-ok from my development server 🥳 🥳 🥳

**Comment by eldadfux** [comment]
🚀 Merged! Thanks @PineappleIOnic !

**Pull request merged**
