### PR TITLE
Feat 535 show hide secrets inside dashboard

### PR DESCRIPTION
**Pull request by kodumbeats**
## What does this PR do?

This PR creates a component which, when applied to an input field, will create a toggle between `element.type="text"` and `element.type="password"`.

## Test Plan

1. Create project
1. Navigate to location of secrets
     1. oAuth
          1. `/console/users/providers?project=###########`
          1. Select an oAuth provider
     1. Webhooks
          1. `/console/webhooks?project=############`
          1. `Add Webhook` -> `Advanced Options` -> HTTP Authentication
     1. Tasks
          1. `/console/tasks?project=############`
          1. `Add Task` -> `Advanced Options` -> HTTP Authentication
1. Success criteria:
    1. Input type of secret field is `password` by default (typing obfuscates characters)
    1. Clicking the `show/hide` button will change input type to `text`

## Work In Progress
- [x] Create secrets component
- [x] Add component to oAuth secrets
- [x] Add component to webhook secrets
- [x] Add component to tasks secrets
- [x] Create changelog
~- [ ] Add `icon-eye-closed` to [fontello config](https://github.com/appwrite/appwrite/blob/master/public/styles/fontello/config.json) and [forms.less](https://github.com/appwrite/appwrite/blob/master/public/styles/forms.less)~
~- [ ] Add toggle between `icon-eye` and `icon-eye-closed`~

## Related PRs and Issues

#535 

## Preview
appwrite-secrets

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes.

### CODE REVIEW

**Comment by kodumbeats** [comment]
Two questions:
- Is it possible to add the `fa-eye-closed` glyph? It would make the toggle a bit nicer looking.
- How do you imagine the toggle looking in webhooks/tasks? Wasn't sure what the UX should be since not all HTTP headers are secrets, for example.

**Comment by eldadfux** [comment]
Hey @kodumbeats,
 
> * Is it possible to add the `fa-eye-closed` glyph? It would make the toggle a bit nicer looking.

I think you can skip any icons for now, and leave the current UI you have. We'll ask our designer to take a look and suggest any changes later.

> * How do you imagine the toggle looking in webhooks/tasks? Wasn't sure what the UX should be since not all HTTP headers are secrets, for example.

I think that at least for now should use the new input only for HTTP passwords.

image

**Comment by eldadfux** [comment]
Awesome work @kodumbeats! I would love to get your feedback about your onboarding experience with our codebase.

**Comment by kodumbeats** [comment]
Since there isn't a whole lot of documentation specifically about developing on the frontend code (home, console, etc), I spent some  time with the litespeed.js repo, repeatedly wishing this doc section was complete:
https://github.com/litespeed-js/litespeed.js/blob/master/docs/get-started.md#create-a-new-view-component

I think some npm scripts would help as well, but it could just be my unfamiliarity with the stack:
- one for compiling javascript with `gulp` (I ended up aliasing `npx gulp build; docker-compose restart appwrite`)
- one for compiling less to css
- one for frontend testing (I see `jest` as a dependency, but couldn't find frontend tests when I looked).

The codebase was quite straight-forward to parse, once I understood where things were. I think ☝🏻 will cover most of the hiccups I encountered. The code itself is simple and a refreshing delight; t'was a pleasure.

Lastly, the [Travis build](https://travis-ci.com/github/appwrite/appwrite/builds/211506799) took 27 minutes to complete. I don't know if that's due to the weight of the `0.7.x` branch and all its cool features, or if I did something wrong, because  #714 mentions a build time of ~10min...

**Comment by eldadfux** [comment]
@kodumbeats thanks for the feedback!!

Yeh, we do plan to improve both Utopia.php and Litespeed.js docs and also build individual websites for both of them :)

We'll also add a new client-side section in our contribution guide with more info about gulp and reloading docker to get changes updated.

We're still missing tests on the client-side of Appwrite, we'll tackle this issue as part of an upcoming redesign process we plan.

The Travis build have some issues in the last few days, maybe related to the new docker pull new limits introduced lately. Current build time has jumped to ~22 minutes and not because of the new version.

**Pull request merged**
