### PR TITLE
Add Norwegian translation

### LINKED ISSUE #105: Missing some Norwegian Translations 🇳🇴
The Norwegian translation was the first one to be added, and we forgot to mention we needed to translate the 'app/config/locale/en.php' file. This is the only file missing before we can add the 'no' locale in the next version.

### PR DESCRIPTION
**Pull request by Niladri24dutta**
## Fixes #105 
- Added `no.php` file in `app/config/locale/` with Norwegian translation

### CODE REVIEW

**Comment by eldadfux** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on Gitter if you would like me to send you some cool Appwrite stickers and magnets!

**Comment by Niladri24dutta** [comment]
> THANK YOU! All changes merged 🥳
> 
> Please reach out to me on Gitter if you would like me to send you some cool Appwrite stickers and magnets!

Sure, how to reach you in gitter?

**Comment by eldadfux** [comment]
Search my name: 'eldadfux' on gitter Search or get to my profile from the Appwrite community page:
https://gitter.im/appwrite/community

**Comment by Niladri24dutta** [comment]
> 
> 
> Search my name: 'eldadfux' on gitter Search or get to my profile from the Appwrite community page:
> https://gitter.im/appwrite/community

Sent you a message in gitter.

**Pull request merged**
