### PR TITLE
Pass custom function $data to execution

### PR DESCRIPTION
**Pull request by kodumbeats**
## What does this PR do?

This PR allows for custom data to be sent to ` /v1/functions/{functionId}/executions`. `$data` is sent as a string via the env `APPWRITE_FUNCTION_DATA` to the function to be decoded in whatever manner.

This also sends the `projectId`, executor's `userId` and generated JWT to the function as well, `APPWRITE_PROJECT_ID`, `APPWRITE_FUNCTION_USER_ID` and `APPWRITE_FUNCTION_JWT`, respectively.

## Test Plan

- Create new cloud function in whatever language that prints the new env vars
- POST some string `$string` in the request body with key `data` to the executions endpoint
    OR
  Execute manually, entering a custom string in the input field.
- Verify that STDOUT matches the input data, and a JWT is created

## Todo

- [x] Update POST to accept `$data`
- [x] Pass `userId` and create JWT for execution 
- [x] Create UI for adding custom data to execution
- [x] Write E2E tests
- [x] Update changelog

## UI Preview

customdatastring

## Related PRs and Issues

#962 
 
### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

yes.

### CODE REVIEW

**Comment by eldadfux** [comment]
Please change the input label in the UI to `Data` or `Custom Data`. And use a textarea instead of an input field.

**Comment by eldadfux** [comment]
@kodumbeats try and take a look at this answer: https://stackoverflow.com/a/45323854/2299554

Your tests look fine. The problem we had in the past, is that the functions worker might need a couple of minutes before the env images are downloaded and ready to use.

View this lines:
https://github.com/appwrite/appwrite/blob/master/app/workers/functions.php#L30-L62

If you could make sure this tests will run after the server-side tests, you should be fine, because we have a timeout there.

**Comment by eldadfux** [comment]
@kodumbeats please post a short gif or a screenshot of the current UI look 🙏🏻

**Comment by eldadfux** [comment]
> o7 Happy to change.
> My personal preference is to name them `APPWRITE_FUNCTION_USERID` and `APPWRITE_FUNCTION_PROJECTID` . Do you prefer having the underscore (e.g. `USER_ID` and `PROJECT_ID`)?

Don't care much as long as we are consisted :)

**Comment by kodumbeats** [comment]
`APPWRITE_FUNCTION_USER_ID` and `APPWRITE_FUNCTION_PROJECT_ID` were more consistent with the rest of the repository, so they were included in https://github.com/appwrite/appwrite/pull/967/commits/90833683faba1dac57c901357c58ddcb672b3ad2.

**Review by TorstenDittmann — APPROVED** [review]
👍🏻

**Review by eldadfux — APPROVED** [review]

**Comment by eldadfux** [comment]
Great work @kodumbeats !!

**Pull request merged**
