### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by arunagri82**
Update README.md

### CODE REVIEW

**Review by Biki-das — COMMENTED** [review]
looks invalid change to them , no typo fix or improvment?

**Comment by arunagri82** [comment]
Grammer error i change the typo

**Comment by eldadfux** [comment]
We love contributions, but we suggest you try and submit more meaningful PRs by exploring any of our [open issues](https://github.com/appwrite/appwrite/issues). If you have any problem or need help, please join our Discord community: https://appwrite.io/discord and use the #hacktoberfest channel.

**Comment by eldadfux** [comment]
@Biki-das, @lohanidamodar thanks for reviewing 🙏

**Pull request closed without merging**
