### PR TITLE
Update code of conduct to Contributor Covenant v2.1

### PR DESCRIPTION
**Pull request by contribootor**
## What does this PR do?

Update code of conduct to Contributor Covenant v2.1

### CODE REVIEW

**Comment by stnguyen90** [comment]
@contribootor We love contributions, but we suggest you try and submit more meaningful PRs by exploring hacktoberfest issues via our [website](https://hacktoberfest.appwrite.io/). If you have any problems or need help, please join our [Discord community](https://appwrite.io/discord) and use the `#hacktoberfest` channel.

**Comment by contribootor** [comment]
Hi @stnguyen90, thank your for your reply.

Why do you think updating code of conduct to a newer version is not meaningful?

**Comment by stnguyen90** [comment]
@contribootor, we'd rather handle the change differently and we're looking for contributions via our hacktoberfest labeled issues as those are more meaningful for us for Hacktoberfest.

**Comment by contribootor** [comment]
@stnguyen90, thank you for your reply again.

> we'd rather handle the change differently
Could you elaborate? How do you wanna handle this differently?

> we're looking for contributions via our hacktoberfest labeled issues
Just to make sure that I get this right, does this mean you only care about hacktoberfest in this month? Even if someone wants to make changes that are useful, you'd rather close it?

**Comment by stnguyen90** [comment]
> Could you elaborate? How do you wanna handle this differently?

This would actually be best in our .github repo instead.

> Just to make sure that I get this right, does this mean you only care about hacktoberfest in this month? Even if someone wants to make changes that are useful, you'd rather close it?

Not exactly. Bug fixes are more than welcome. However, because we have hundreds of issues and PRs during Hacktoberfest, we need to clear the queue quickly.

**Comment by contribootor** [comment]
Gotcha. Makes sense

**Pull request closed without merging**
