### PR TITLE
Provided brotli support.

### PR DESCRIPTION
**Pull request by Rohitub222**

### CODE REVIEW

**Comment by eldadfux** [comment]
Hey @Rohitub222 I see you managed to send the PR successfully :)

As you can see the CI build is failing because the Brotli installation isn't working because we don't have the unzip command on the server (trying to keep the final docker image light as possible):
https://travis-ci.org/github/appwrite/appwrite/builds/685611478#L2813

You can try and install Brotli using APT-GET, it seems more reliable than downloading it from an unofficial 3rd party source. You can check the example here: 
https://docs.nginx.com/nginx/admin-guide/dynamic-modules/brotli/

**Comment by Rohitub222** [comment]
Hi @eldadfux I have updated the brotli installation using apt-get ( thanks for the doc ).

**Comment by eldadfux** [comment]
Hey @Rohitub222 build is still failing, I think it will be easier for you to test this locally.

**Comment by PedroCisnerosSantana** [comment]
Hello @Rohitub222 seems like there's an error with the nginx module brotli, take a look at this [https://serverfault.com/questions/976735/how-to-install-the-brotli-nginx-module-properly-on-debian](url), hope it helps you 😉

**Comment by eldadfux** [comment]
@PedroCisnerosSantana We were thinking about installing it from the source of the official repo: 
https://github.com/google/brotli

**Comment by PedroCisnerosSantana** [comment]
@eldadfux why don't we just use a brotli docker? [check this](https://hub.docker.com/r/thecarlo/nginx-brotli/dockerfile)

**Comment by eldadfux** [comment]
@PedroCisnerosSantana actually that can be a very good reference... what do you say @Rohitub222 ?

**Comment by Rohitub222** [comment]
@PedroCisnerosSantana thank you for the links they were very helpful.
Regarding brotli docker i would like to try it out first then see if we can
go ahead with it. I would ping you the status in a  couple of days. What do
you suggest @eldadfux ?

**Comment by eldadfux** [comment]
Hey @Rohitub222, any updates?

**Comment by eldadfux** [comment]
Closed in favour of #405. @Rohitub222 please review the new PR to see if you have any inputs.

**Pull request closed without merging**
