### PR TITLE
Fix: event multi-execution

### PR DESCRIPTION
**Pull request by Meldiron**
## What does this PR do?

With this PR, if multiple functions execute with an event, they will all attempt to be executed instead of stopping when one execution fails. Use case explained well in the issue linked below.

I believe this is the correct behavior, as we don't have a function chaining feature in Appwrite.

## Test Plan

- [x] Manual QA

CleanShot 2022-08-17 at 15 36 52

CleanShot 2022-08-17 at 15 36 35

## Related PRs and Issues

https://github.com/appwrite/appwrite/issues/3666

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes 😇

### CODE REVIEW

**Comment by eldadfux** [comment]
Why is this even causing the issue? shouldn't it be handled by our default error handler for workers?

**Comment by Meldiron** [comment]
@eldadfux The problem is that if an event comes into a function worker, and there are multiple functions that need to be executed for this event... Well, if the first execution fails, then no other will run. It could fail, for instance, when a function does not have deployment yet.

Sooo yes, the worker will handle the error and work on the next task in the queue. But in one task, it was supposed to execute 5 functions, but it only executed one and stopped due to an exception.

Does it make sense?

**Comment by eldadfux** [comment]
Do we have 5 tasks in a single task because or our new event model? Have we considered pushing 5 tasks for 5 events instead of running 5 events in one task? What is the max amount of events we can have in the same task?

**Comment by stnguyen90** [comment]
@eldadfux, when an event comes in for the function worker to process, it loops through each function to check execute the event. If one function throws an exception, the for loop fails to finish iterating over all functions.

**Comment by Meldiron** [comment]
@eldadfux  Regarding maximum executions under one event, that is limited as far as I am concerned. For instance, document create: `databases.*.collections.*.documents.*`

There are 3 dynamic parts that can either be specific ID or wildcard. That makes a combination of 8 options if I am not mistaken. For 4 dynamic parts it would be 16, for 5 it would be 32.

**Review by christyjacob4 — APPROVED** [review]
Let's change the target branch to 1.3.x

**Pull request merged**
