### PR TITLE
Feat 401 OIDC auth

### PR DESCRIPTION
**Pull request by mKlooney**
## What does this PR do?

This PR adds the ability to use an custom OpenID Connect Provider for authentication.
Therefore a custom form was added, so a user is able to provide in addition to the AppId and AppSecret also the [Discovery Endpoint](https://openid.net/specs/openid-connect-discovery-1_0.html). This endpoint is then used to optain the required endpoints (auth, token, userinfo) automatically.

## Test Plan

Setup or use an Identity Provider with OpenID Connect and OpenID Connect Discovery support.
Enable OIDC provider in Appwrite console by providing App ID, App Secret and Discovery endpoint.
Authenticate with a user provided by the OIDC Server.

In case App Secret or Discovery is not provided or not accessible => Error 412 is returned (Provider is disabled).

## Related PRs and Issues

The following Issues could be solved with this PR and OpenID Connect:
Fixes [1668](https://github.com/appwrite/appwrite/issues/1668)
Fixes [2701](https://github.com/appwrite/appwrite/issues/2701)
Fixes [1778](https://github.com/appwrite/appwrite/issues/1778)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

YES

### CODE REVIEW

**Comment by christyjacob4** [comment]
Hey @mKlooney  Thank you so much for the contribution! This is amazing work. We will review this soon

**Comment by mKlooney** [comment]
Hey @christyjacob4! I've updated this PR with the latest changes from the main repo. Let me know if there's anything I can help you with!

**Review by eldadfux — CHANGES_REQUESTED** [review]
@mKlooney thanks for this awesome PR! One notable thing that I have noticed is that we need to set the adapter setting with env vars. Although that might be enough to work, it does not support Appwrite multi-tenancy. For this, we need to make sure the settings are set per project, similar to how the Apple authentication works.

**Comment by mKlooney** [comment]
Hey @eldadfux and @christyjacob4, I modified my PR so it is possible to configure an OIDC provider per project.
I removed the env vars and introduced a custom form (like introduced by this merged [PR](https://github.com/appwrite/appwrite/pull/2624)) to be able to configure next to App ID and App Secret also the Discovery Endpoint.
I hope you like this solution better.🤞

**Comment by mKlooney** [comment]
> Hey @eldadfux and @christyjacob4, I modified my PR so it is possible to configure an OIDC provider per project.
> I removed the env vars and introduced a custom form (like introduced by this merged [PR](https://github.com/appwrite/appwrite/pull/2624)) to be able to configure next to App ID and App Secret also the Discovery Endpoint.
> I hope you like this solution better.🤞

Hi @eldadfux do you have any feedback for me?
Is there anything I could help you with?

**Review by mKlooney — COMMENTED** [review]
All requested changes are done.

**Pull request closed without merging**
