### PR TITLE
Fixed an obsolete path

### PR DESCRIPTION
**Pull request by midopooler**
In the doc, https://github.com/appwrite/appwrite/blob/master/docs/references/account/create-verification.md
the URL which directs you to verification is https://github.com/appwrite/appwrite/blob/master/docs/client/account#updateAccountVerification
where the path "docs/client" doesn't exist in the repo. On further investigation, I found the appropriate doc to be at "docs/references/account/update-verification.md" and hence, this PR.

### CODE REVIEW

**Comment by midopooler** [comment]
@eldadfux have a look?

**Review by shivaylamba — APPROVED** [review]

**Comment by eldadfux** [comment]
Hey @midopooler this link isn't referencing the markdown file, but the URL on our docs site: https://appwrite.io/docs.

We'd love to get other PRs from you, please take a look at other open issues.

**Comment by midopooler** [comment]
@eldadfux Seems like you didn't get the meaning behind this PR. 
The link on the mentioned docs is giving a 404 error. that's why I'm doing the path changes. 

> We'd love to get other PRs from you, please take a look at other open issues.
Yeah sure, I would love to contribute.

**Comment by eldadfux** [comment]
@midopooler yeh, I know. Another PR was raised by another contributor (#675) with the correct link.

**Pull request closed without merging**
