### PR TITLE
Updated dependencies, compressed some imgs, and README edit.

### PR DESCRIPTION
**Pull request by Mou-Ikkai**
An assortment of changes, including updating your REALLY outdated dependencies. Some were even 1.x behind!

### CODE REVIEW

**Comment by Mou-Ikkai** [comment]
I'll try to fix this if... my change is at fault.

**Comment by Mou-Ikkai** [comment]
Found it. Latest ubuntu version breaks something.

**Comment by Mou-Ikkai** [comment]
Right... PHP likes changing things each version so you have to rewrite code...

**Comment by eldadfux** [comment]
@Mou-Ikkai please note that some of your changes are already applied to our latest in-development version located at branch 0.7.x.

You should work against that branch and not the master.

Also, please don't manipulate any images inside the `./tests` directory as it might break the tests and has no performance advantage.

**Comment by Mou-Ikkai** [comment]
Will do.

**Pull request closed without merging**
