### PR TITLE
Fixed some typos and grammatical errors in 3 files

### PR DESCRIPTION
**Pull request by HVbajoria**
## What does this PR do?
This PR fixes typos and grammatical errors in 3 files.
The 3 files are :
1) docs/tutorials/add-environment-variable.md
2) docs/tutorials/add-storage-adapter.md
3) docs/tutorials/add-oauth2-provider.md

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
Yes 

Please check and let me know if any changes are required.
Thank you.
Happy Hacktoberfest.

### CODE REVIEW

**Comment by HVbajoria** [comment]
Yes @Biki-das sir as I had corrected typos like variable spelling was written wrong and there were some extra "s" which made it grammatically incorrect I also made those changes. 
Could you please check it once. 
Thank you

**Comment by Biki-das** [comment]
> Yes @Biki-das sir as I had corrected typos like variable spelling was written wrong and there were some extra "s" which made it grammatically incorrect I also made those changes. Could you please check it once. Thank you

well the typo fix is acceptable but those were not actually grammatically incorrect

**Comment by HVbajoria** [comment]
Okay sir then should I remove the second and third file if that works @Biki-das ?

**Comment by Biki-das** [comment]
@HVbajoria seems like you tried to use grammarly and pasted the whole doc on it , we appreciate your contribution but all of these does not make up to a meaningful contribution if you want help to work on issues ping me up and try looking on something from the issues section

**Comment by Biki-das** [comment]
> Okay sir then should I remove the second and third file if that works @Biki-das ?

well no need as of now let the official maintainers decide what they want to do with your PR and no need to call me "sir" just ping me name and thats it 😊

**Comment by HVbajoria** [comment]
Okay @Biki-das sir. 
Sorry for the inconvenience caused. 
Should I close this issue ?

**Pull request closed without merging**
