### PR TITLE
Adding missing audits.userId to routes

### PR DESCRIPTION
**Pull request by singhbhaskar**
## What does this PR do?

This PR resolves issue(https://github.com/appwrite/appwrite/issues/5070) by adding the audit.userId to routes. The stated that OAuth2 Redirect route had this issue but few other routes was also missing the label. Hence, I have added the label to routes missing this label.

Closes: https://github.com/appwrite/appwrite/issues/5070

## Test Plan

I had ran unit test cases and e2e test.

## Related PRs and Issues

- Issue: https://github.com/appwrite/appwrite/issues/5070

## Checklist

- [x] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [x] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

### CODE REVIEW

**Review by stnguyen90 — CHANGES_REQUESTED** [review]
@singhbhaskar thanks for raising this PR! Would you please include a screenshot of the session create event working and the data showing up in the audit logs?

**Comment by singhbhaskar** [comment]
Hey @stnguyen90 ,

Adding the screenshot. Please check it.
Screenshot 2023-02-19 at 8 47 06 PM

**Review by stnguyen90 — APPROVED** [review]
Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

**Review by TorstenDittmann — APPROVED** [review]

**Comment by singhbhaskar** [comment]
Thanks @stnguyen90 and app-write team, excited to work on other issues as well. Cheers 🎊

**Pull request merged**
