### PR TITLE
feat(database): add collection enable/disable

### PR DESCRIPTION
**Pull request by TorstenDittmann**
## What does this PR do?

- adds enable/disable to collections

## Test Plan

- added tests

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

### CODE REVIEW

**Review by kodumbeats — CHANGES_REQUESTED** [review]
1) I had to go looking for `App::setResource('mode')` to know what `$mode` was being injected to the route - can we add some comments?

2) Do we care about adding this functionality to attributes/indexes routes?

**Comment by TorstenDittmann** [comment]
> 



> 1. I had to go looking for `App::setResource('mode')` to know what `$mode` was being injected to the route - can we add some comments?
> 2. Do we care about adding this functionality to attributes/indexes routes?

1. Gonna add some comments to the resource 👍🏻 
2. Don't think we wanna add it - at least at this point

**Comment by wess** [comment]
is "mode" a bit to generic for the naming?

**Comment by TorstenDittmann** [comment]
> is "mode" a bit to generic for the naming?

Maybe 🤔  we can keep that in mind for the future.

**Review by kodumbeats — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
