### PR TITLE
Added ESLint

### PR DESCRIPTION
**Pull request by iamrajiv**
Fixes: #586

### CODE REVIEW

**Comment by iamrajiv** [comment]
@eldadfux Please review.

**Comment by Kolkies** [comment]
What is your benefit of implementing ESLint?

**Comment by iamrajiv** [comment]
@Kolkies ESLint is a static code analysis tool for identifying problematic patterns found in JavaScript code:
- You will find bugs and errors before they happen.
- You will spend less time testing new features.
- Your code (and your team's code) will be more consistent.

**Comment by Kolkies** [comment]
I know what ESLint does, but why would you spend less time testing new features?

Also don't we need a eslint file with the rules?

**Comment by iamrajiv** [comment]
@Kolkies, For now, I do not think we need ESLint rules but I am open for suggestions.

**Comment by Kolkies** [comment]
Why are you making a pull request then?

**Comment by iamrajiv** [comment]
@Kolkies Whenever there is a push or PR to the master branch than ESLint will check the JavaScript code if it is well-formatted or not so that maintainer does not have to get thought the whole code to check for that. I will be adding `eslint.yml` file in workflows.
```yml
name: ESLint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  eslint:
    name: ESLint Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: rm -f .yarnclean
      - run: yarn --frozen-lockfile --ignore-engines --ignore-optional --no-bin-links --non-interactive --silent --ignore-scripts --production=false
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          HUSKY_SKIP_INSTALL: true
      # Alternative: if you use npm instead of yarn
      # - run: npm ci --no-audit --prefer-offline
      - uses: tinovyatkin/action-eslint@v1
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          check-name: eslint # this is the check name from above 👆 where to post annotations
```

**Comment by Kolkies** [comment]
I know, but why implement eslint without rules

**Comment by Kolkies** [comment]
Without rules eslint does not do anything afaik

**Comment by iamrajiv** [comment]
@Kolkies Rules are already been defined in this https://github.com/tinovyatkin/action-eslint.

**Comment by Kolkies** [comment]
Oh ok, didnt know that, my bad

**Comment by iamrajiv** [comment]
@Kolkies Can you add Hacktoberfest label to it?

**Review by Kolkies — APPROVED** [review]

**Comment by eldadfux** [comment]
We're currently rethinking the UI and build process so this might have to wait.

**Pull request closed without merging**
