### PR TITLE
Good first issue 1784 help by implementing epic games o auth

### PR DESCRIPTION
**Pull request by sshiv5768**
## What does this PR do?
1: Added new Epic games provider array into ```app/config/providers.php```.
2: Added logo of Epic games in ```public/images/users```
3: Added new oAuth provider class named in ```src/Appwrite/Auth/OAuth2```

### CODE REVIEW

**Comment by christyjacob4** [comment]
@sshiv5768  Step 1 and 2 look good. I believe you're working on the OAuth provider itself now. Let us know on Discord if you need any help.

**Comment by sshiv5768** [comment]
@christyjacob4 yeah, actually got little bit busy but now back on the track to complete this issue.

**Comment by christyjacob4** [comment]
Alright! Looking forward to reviewing it soon :)

**Comment by sshiv5768** [comment]
Hey, @christyjacob4 I made some changes and added EpicGames.php class in Oauth providers. Can you please review it.

**Comment by eldadfux** [comment]
> Actually, when i am going to try the Appwrite using Docker it is giving me an error. Is there any other way to test the workflow?

You have to get Appwrite working to test it. What exact error are you getting?

**Comment by christyjacob4** [comment]
@sshiv5768 I'll be closing this PR for now since there has been no activity on it. Feel free to reopen it if you would like to start working on it again 😃

**Pull request closed without merging**
