### PR TITLE
Wildcard for hostname

### PR DESCRIPTION
**Pull request by Meldiron**
🚨 Utopia/framework release required before merge 🚨

## What does this PR do?

We currently don't support hostname syntax `*.myweb.com` to allow all subdomains. With this PR, you can start using the wildcard symbol `*` for sections where you want to allow any value.

I also added a proper validator, so people are warned when trying to add hostname like `http://myapp.com` or `myapp:8000`.

## Test Plan

The validator is properly tested at the library level. Current tests should pass.

- [x] Manual QA:
image

Before:

image

After: 

CleanShot 2022-03-28 at 11 18 15

(using `https://8080-tringug-authmodal-8l5p3rlrnxe.ws-eu38xl.gitpod.io/examples/appwrite.html` URL)

- [x] Validator QA:

CleanShot 2022-03-28 at 11 58 57

## Related PRs and Issues

https://github.com/appwrite/appwrite/issues/2939

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

✅

### CODE REVIEW

**Comment by eldadfux** [comment]
I like the feature. It would be great if we could encapsulate this logic inside a Utopia validator with proper tests.

**Comment by eldadfux** [comment]
Let's add more information in the UI placeholder that allows devs to understand this feature better.

**Comment by Meldiron** [comment]
The PR is outdated, I am going to update it 😇

**Comment by Meldiron** [comment]
This PR is a mess, also really old. Closing it, here is a new PR: https://github.com/appwrite/appwrite/pull/3124

**Pull request closed without merging**
