### PR TITLE
Refactor Apple OAuth2 getUserName retrieval logic

### LINKED ISSUE #7268: 🐛 Bug Report: Sign in with Apple, user name should not be email
### 👟 Reproduction steps

Sign in with Apple to any app, you will get user information, in this information you get email as name instead of name itself.

Scope details for Sign in with Apple: ['email', 'name']

### 👍 Expected behavior

In Sign in with Apple, only on first time login/registration does the app get the name information (if the user has given permission to share). For logins after the first login, the name information is blank (Apple only provides this information the first time). The developer must handle the name information themselves.

### 👎 Actual Behavior

Name information always comes as an e-mail.

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

One-click Digital Ocean droplet

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by xuelink**
## What does this PR do?

Fixes #7268 

Ref to this [doc](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/incorporating_sign_in_with_apple_into_other_platforms#3332115) user format

## Test Plan

Sign in with Apple to test fetching name or not

## Checklist

- [x] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [x] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

### CODE REVIEW

**Review by stnguyen90 — COMMENTED** [review]
Nice work! Would you be able to show some screenshot(s) of it working successfully?

**Comment by behics** [comment]
Even if i try to give scope `name`, `$this->claims` returns
```php
Array
(
    [iss] => https://appleid.apple.com
    [aud] => service.com.appwrite.testapp
    [exp] => 1708257457
    [iat] => 1708171057
    [sub] => 000201.4c58eaf074f54eada4d5fe7cf89bf1a7.1559
    [at_hash] => Pe6QnaTkbskuyc2SjzHOLw
    [email] => kmfyt85xzw@privaterelay.appleid.com
    [email_verified] => 1
    [is_private_email] => 1
    [auth_time] => 1708171056
    [nonce_supported] => 1
)
```

However, according to this [docs](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/incorporating_sign_in_with_apple_into_other_platforms), it should work otherwise it returns empty string as well. 

Returning `email` as a Name paramater of Auth User, completely replaced with returning `name` with all other OAuth2 services.

Best

**Comment by stnguyen90** [comment]
@behics, from what I've read, the name is only provided the first time the user authorizes the OAuth2 app. Every subsequent time, only email is returned. Was your test a fresh authorization or had you authenticated once before?

**Comment by raman04-byte** [comment]
Is there any update on this?
I am doing OAuth using Apple and need name.

**Comment by stnguyen90** [comment]
> disconnected auth from apple settings and tried it again

@behics what do you mean by this? Did you disconnect in Appwrite? I was referring to making sure it's the first the the end user authorizes the oauth app.

**Comment by behics** [comment]
> > disconnected auth from apple settings and tried it again
> 
> @behics what do you mean by this? Did you disconnect in Appwrite? I was referring to making sure it's the first the the end user authorizes the oauth app.

Yes its the first end user authorizes the oath app. 

To test it again, i disconnect user totally between appwrite and "sign-in-with-apple"
Before i start to test it,

1- deleted "user which signed in with apple" in appwrite
2- stop user related apple id to "stop using apple ID"
3- try it again from over

Screenshot 2024-03-20 at 3 27 29 AM

**Comment by stnguyen90** [comment]
@behics, dang...that is infuriating! I'll try to find some time to test myself as well.

**Comment by xuelink** [comment]
> @behics, dang...that is infuriating! I'll try to find some time to test myself as well.

@stnguyen90 unfortunately, apple restrictions make it harder to test it

**Comment by stnguyen90** [comment]
Closing PR as this doesn't work.

**Pull request closed without merging**
