### PR TITLE
Typo mistake fixed

### PR DESCRIPTION
**Pull request by toir427**
Typo mistake fixed

### CODE REVIEW

**Comment by vj-codes** [comment]
I don't think that's a typo, it is grammatically correct the way it is.

**Comment by toir427** [comment]
I thought they used contributing as gerund but it comes as a noun. you mean that?

**Comment by stnguyen90** [comment]
@toir427, this is correct as is. Also, we suggest you try and submit more meaningful PRs by exploring hacktoberfest issues via our [website](https://hacktoberfest.appwrite.io/). If you have any problems or need help, please join our [Discord community](https://appwrite.io/discord) and use the `#hacktoberfest` channel.

**Comment by toir427** [comment]
> @toir427, this is correct as is. Also, we suggest you try and submit more meaningful PRs by exploring hacktoberfest issues via our [website](https://hacktoberfest.appwrite.io/). If you have any problems or need help, please join our [Discord community](https://appwrite.io/discord) and use the `#hacktoberfest` channel.

I just realized that after I had created this PR

**Pull request closed without merging**
