### PR TITLE
Add missing Ukrainian translations

### PR DESCRIPTION
**Pull request by andrii-bodnar**
## What does this PR do?

This PR adds missing Ukrainian translations

### CODE REVIEW

**Review by christyjacob4 — APPROVED** [review]

**Comment by christyjacob4** [comment]
@andrii-bodnar thanks a lot for the PR!! Could you also update the [CHANGES.md](https://github.com/appwrite/appwrite/blob/master/CHANGES.md) file with your changes?

**Comment by andrii-bodnar** [comment]
@christyjacob4 sure, just updated the changelog

**Comment by andrii-bodnar** [comment]
@christyjacob4 could you please review it?

**Comment by andrii-bodnar** [comment]
Hi @christyjacob4, just rebased the branch, could you please review it?

**Comment by andrii-bodnar** [comment]
@christyjacob4 what about merging this?

**Pull request closed without merging**
