### PR TITLE
Fixed Oauth2 port issue

### PR DESCRIPTION
**Pull request by dro-1**
## What does this PR do?
It adds the port number to OAuth callback URLs

## Test Plan
I had to change the port forwarding of traefik in the docker-compose.yml file to 3000:80 on line 24.
I added the port numbers to each route using $request->getPort()
I started the server with docker-compose up -d
I then tested the Oauth in a React app I was building and it worked as expected.

Before making the commit, I changed the traefik port back to 80:80

## Related PRs and Issues

It fixes this [issue](https://github.com/appwrite/appwrite/issues/2365)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes, I have

### CODE REVIEW

**Review by eldadfux — CHANGES_REQUESTED** [review]
You can't assume we should append the port in any case. If port 80 or 443 are used, we should skip the port from the URL. Similar example is available here: https://github.com/appwrite/appwrite/blob/25b03c90f8eb5655d0a2ccc6a3f83b9c10d3edec/app/controllers/shared/web.php#L25

**Comment by dro-1** [comment]
Ohh. Thanks for the feedback

**Comment by dro-1** [comment]
I've corrected the code but I don't think the test is correct.

**Comment by dro-1** [comment]
I'm also having issues running the test. If I try to run it when the container is up, I get this error
image
If I run it when the container is down, I don't get any feedback

**Comment by christyjacob4** [comment]
@dro-1  I think the error is caused due to the appwrite container not running. Can you ensure that all the containers are working fine ? 


Also, let us know if you are still working on this .

**Comment by stnguyen90** [comment]
@dro-1, will you still be able to continue work on this PR?

**Comment by dro-1** [comment]
I'm sorry @stnguyen90 but I don't think I'd be able to continue. I am currently swamped with some other projects. I hope I'll still be allowed to contribute when I find the time.

**Comment by stnguyen90** [comment]
Closing for now, but feel free to reach out again if you want to jump back on this and it's still open!

**Pull request closed without merging**
