### PR TITLE
Add float validator case to spec to prevent fallthrough

### PR DESCRIPTION
**Pull request by abnegate**
## What does this PR do?

SDK method's required string parameters for `min`, `max`, `default` when calling `createFloatAttribute` or `createIntegerAttribute`, setting `$loose = true` when constructing the validators will allow those calls to succeed.

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

Closes https://github.com/appwrite/sdk-for-kotlin/issues/17

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by TorstenDittmann** [comment]
Shouldn't the SDK send the actual float value instead of a String? 🤔

**Comment by christyjacob4** [comment]
@TorstenDittmann doesn't the POST body automatically get converted to a string nevertheless ??  👀

**Comment by eldadfux** [comment]
> @TorstenDittmann doesn't the POST body automatically get converted to a string nevertheless ?? 👀

The JSON payload on POST should return correct types.

**Comment by eldadfux** [comment]
We probably need to have the same for the open-api 3 class.

**Review by eldadfux — APPROVED** [review]

**Comment by eldadfux** [comment]
Thanks @abnegate!

**Pull request merged**
