### PR TITLE
feat: Added new country `Taiwan` with its translations

### LINKED ISSUE #7868: 🚀 Enhancement: Missing Country for Locale endpoint -- User Inquiry Regarding Addition of Taiwan to Countries List
### 🔖 Enhancement description

Adding a new country "Taiwan"

### 🎤 Pitch

Hey everyone

One of our users has recently raised an issue regarding the selection of their country within the app. They have expressed a desire to see Taiwan added to the list of available countries.

As per the conversation provided by the user, they have expressed their concern about not being able to select Taiwan and instead having to choose China as an alternative. They have also mentioned that they understand the complexities involved in adding a new country to the app and have kindly requested any updates or insights into the progress of this issue.

Our user's satisfaction is of utmost importance to us, and we strive to address their concerns promptly. Therefore, I would like to inquire if there are any plans or timelines in place for the addition of Taiwan to the countries list. Additionally, if there are any updates or progress regarding this matter, we would appreciate being kept informed so that we can provide our user with the necessary information.

Thank you for your attention to this matter and for your commitment to improving the user experience of the app. We look forward to your response and the potential inclusion of Taiwan in the countries list.

Best

Discord Thread: https://discord.com/channels/564160730845151244/1215561933550518342

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by xuelink**
## What does this PR do?

This PR adds a new country to the locale endpoint, providing all the necessary translations.

Fixes #7868

## Test Plan
The screenshot below shows the successful addition of the new country to the `locale` endpoint:

Screenshot 2024-03-28 at 12 32 06 AM

You can also view the response in this [response.json](https://github.com/appwrite/appwrite/files/14781381/response.json) file.

## Related PRs and Issues

- #7868

## Checklist

- [x] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [x] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

### CODE REVIEW

**Review by stnguyen90 — CHANGES_REQUESTED** [review]
Looks great! I spot checked a few and they look accurate. 

The only problem is the tests. It seems some tests have broken (probably because they used that countries API. Would you please fix the tests?

**Comment by xuelink** [comment]
> Looks great! I spot checked a few and they look accurate.
> 
> The only problem is the tests. It seems some tests have broken (probably because they used that countries API. Would you please fix the tests?

Yea test logs exactly what you say: ```Failed asserting that 195 matches expected 194.```

**Comment by xuelink** [comment]
@stnguyen90 Feel free to run these tests again

**Comment by xuelink** [comment]
@stnguyen90 i dont know how to pass this test. Can you please take a look and give me a clue about it ? Best

**Review by stnguyen90 — APPROVED** [review]

**Comment by stnguyen90** [comment]
Since TW is included in [ISO 3166](https://www.iso.org/obp/ui/#iso:code:3166:TW), we're going to add it to our list too.

**Comment by xuelink** [comment]
We are waiting for the new release including this merged PR. Best

**Pull request merged**
